#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import json
import re
from collections import Counter

def is_chinese_only(text):
    """检查文本是否只是中文（不包含日文假名）"""
    if not text:
        return False
    if re.search(r'[\u3040-\u309F\u30A0-\u30FF]', text):
        return False
    return re.search(r'[\u4e00-\u9fa5]', text) is not None

def translate_zh_to_en(text):
    """中文到英文翻译 - 使用我的翻译能力"""
    if not text or not text.strip():
        return ""
    
    # 保存题号
    text = text.strip()
    number_match = re.match(r'^(\d+)\.\s*', text)
    prefix = number_match.group(0) if number_match else ''
    content = re.sub(r'^\d+\.\s*', '', text)
    
    # 处理explanation标准开头
    if content.startswith('根据题目描述，该说法是正确的'):
        rest = re.sub(r'^根据题目描述，该说法是正确的。\s*', '', content)
        return prefix + 'According to the question description, this statement is correct. ' + translate_zh_to_en(rest)
    elif content.startswith('根据题目描述，该说法是错误的') or content.startswith('根据题目描述，该说法是误的'):
        rest = re.sub(r'^根据题目描述，该说法是(错误的|误的)。\s*', '', content)
        return prefix + 'According to the question description, this statement is incorrect. ' + translate_zh_to_en(rest)
    
    if content in ['如题所述', '如题目所述']:
        return prefix + 'As stated in the question'
    
    # 使用规则进行翻译
    result = content
    
    # 扩展的翻译规则 - 我会使用我的翻译能力为每个文本创建准确的翻译
    # 由于文本数量很大，我会使用更智能的翻译方法
    
    # 扩展的完整句子翻译（优先匹配长句子）
    full_sentence_translations = {
        '从后面看，图中的手势信号是右转弯、掉头或在同一方向行驶中向右改变车道的信号': 'From behind, the hand signal in the figure is a signal for right turn, U-turn, or changing lanes to the right while driving in the same direction',
        '在坊碍交通的时候，即使在未禁止的地方，也不能横穿道路或掉头': 'When obstructing traffic, even in places where it is not prohibited, you must not cross the road or make a U-turn',
        '在前方道路有障碍物的时候，应当提前减速或停车，给对面来车让道': 'When there is an obstacle on the road ahead, you should slow down or stop in advance to yield to oncoming vehicles',
        '在交叉路附近以外的道路行驶的车辆，在有紧急车辆驶近时，如果靠左侧让行，一定要暂时停车': 'Vehicles driving on roads other than near intersections must temporarily stop when an emergency vehicle approaches if yielding to the left',
        '右转弯时，如果反方向有直行车辆驶来，即使自己的车已先进入交叉路，也不可妨碍直行车的通行': 'When turning right, if a straight-going vehicle approaches from the opposite direction, even if your vehicle entered the intersection first, you must not obstruct the passage of the straight-going vehicle',
        '内轮差是指，汽车在右转弯时，后轮比前轮更靠外侧': 'Inner wheel difference refers to when a car turns right, the rear wheels are more to the outside than the front wheels',
        '在普通道路的法定最高速度，所有的机动车都是每小时60公里': 'On ordinary roads, the legal maximum speed for all motor vehicles is 60 kilometers per hour',
        '申考大型驾驶证的原则需具备以下条件：年龄在21岁及以上，且取得普通驾驶证期间合计3年及以上。不过，若是修完政令指定教程的人员，19岁及以上且取得普通驾驶证期间合法1年及以上即可申考': 'The principle for applying for a large vehicle license requires the following conditions: age 21 or older, and having held an ordinary license for a total of 3 years or more. However, for those who have completed government-designated courses, 19 years or older with 1 year or more of valid ordinary license experience is sufficient',
        '为进出临近道路的场所内横穿人行道和路侧带时，如果没有行人通行，不必在人行道和路侧带前暂时停车': 'When crossing sidewalks and roadside strips to enter or exit road-facing places, if there are no pedestrians, temporary stops before sidewalks and roadside strips are not necessary',
        '有图中标志的道路，原则禁止车辆通行，但在路旁有车库的车辆等，取得警察署的许可后，车辆可缓行通过': 'Roads with the sign shown in the figure are generally prohibited for vehicles, but vehicles with garages along the road can pass slowly after obtaining permission from the police station',
        '在这个标志的场所,不能停泊车或临时停车': 'At places with this sign, parking or temporary parking is not allowed',
        '落石危险': 'Rockfall danger',
        '在视线较差的左弯道上,靠中央线行驶能够迅速确认弯道前方,因此很安全': 'On left curves with poor visibility, driving near the center line allows quick confirmation of the curve ahead, making it safe',
        '下雨的时候,空走距离变长,但是制动距离不变': 'When it rains, the free-running distance becomes longer, but the braking distance does not change',
        '以每小时 60 公里的速度猛烈撞击钢筋混凝土墙壁时,会受到和从 5 层程度建筑物落下(大约 14 米)时相同程度的冲击': 'When hitting a reinforced concrete wall at 60 kilometers per hour, you will receive the same impact as falling from a 5-story building (approximately 14 meters)',
        '中央线不一定设置在道路中央': 'The center line is not necessarily set in the center of the road',
        '在有信号灯的交叉路想往右转弯的时候,因对面是绿灯进入了交叉路，但右转弯方向的信号是红灯的，此时在交叉路中停下来了': 'When wanting to turn right at an intersection with traffic lights, you entered the intersection because the opposite signal was green, but the signal in the right turn direction was red, so you stopped in the intersection',
        '右转弯时 要在交叉路跟前靠道路中央行驶': 'When turning right, you should drive near the center of the road before the intersection',
        '由于车辆的重心会升高或失去平衡，容易侧翻,因此货物应当尽量装在低处，并保持左右平衡': 'Because the vehicle\'s center of gravity will rise or lose balance, making it prone to rollover, cargo should be loaded as low as possible and maintain left-right balance',
        '任何情况都不能在高速上停车': 'Under no circumstances should you park on the expressway',
        '驾驶员应尊重行人与其他驾驶员的立场,本着相互礼让的原则通行': 'Drivers should respect the position of pedestrians and other drivers, and pass based on the principle of mutual courtesy',
        '绿灯因为不是前进的命令,所以在交叉路，人行横道，铁路道等地方,就出不来的交通状态的时候，即使是绿灯也不能进入': 'Because a green light is not a command to proceed, at intersections, pedestrian crossings, railroad crossings, etc., when traffic conditions prevent exit, you cannot enter even with a green light',
        '即使以同样的速度行走，也会感到夜间比白天慢': 'Even at the same speed, it feels slower at night than during the day',
        '在交叉路左转弯时,左后方有自行车快速接近,因为有可能刮到,所按喇叭抢先左转': 'When turning left at an intersection, a bicycle is quickly approaching from the left rear, so I honked and turned left first to avoid collision',
        '在禁止停泊车的道路上停车并在车中等待友人 5 分钟的行为是非法停车': 'Parking on a road where parking is prohibited and waiting in the car for a friend for 5 minutes is illegal parking',
        '在转弯时,与速度无关,一定会产生内轮差': 'When turning, regardless of speed, inner wheel difference will definitely occur',
        '在交叉路附近通行时，因为紧急车辆接近，所以靠左侧放慢了速度': 'When passing near an intersection, because an emergency vehicle was approaching, I slowed down to the left',
        '驾驶执照的条款栏上所记载的「眼镜等」含使用隐形眼镜': 'The "glasses, etc." noted in the driver\'s license terms includes the use of contact lenses',
        '因为前方车辆发出了右转弯信号准备向右侧改变车道，所以鸣笛提醒其注意后，从右侧超了过去': 'Because the vehicle ahead signaled a right turn and prepared to change lanes to the right, I honked to alert it and then passed from the right',
        '由于气温下降，如果在家前面的道路上泼水的话有可能使道路结冰，但为了防止起灰泼了水': 'Due to temperature drop, if water is splashed on the road in front of the house, the road may freeze, but water was splashed to prevent dust',
        '在单行路上给紧急车辆让路时，有时要靠向道路的右侧': 'When yielding to emergency vehicles on a one-way road, sometimes you need to move to the right side of the road',
        '过度地鸣笛不仅产生噪音还刺激对方的情绪，是引起麻烦的原因': 'Excessive honking not only creates noise but also irritates others, causing trouble',
        '面对该信号的车辆及有轨电车，不能越过停车位置前行': 'Vehicles and streetcars facing this signal cannot proceed beyond the stopping position',
        '通过自行车的侧面在交叉路左转弯时，因为有将自行车卷入的危险，所以鸣笛提醒自行车注意后先向左转弯了': 'When turning left at an intersection passing beside a bicycle, because there is a risk of involving the bicycle, I honked to alert the bicycle and then turned left first',
        '在同一方向有三条车辆通行带的道路上，驾驶普通汽车一直在左数第三条通行带上行驶了': 'On a road with three vehicle lanes in the same direction, I drove an ordinary car in the third lane from the left',
        '普通汽车在没有用标志或标示指定的普通公路上的最高限速是时速60公里': 'The maximum speed limit for ordinary cars on ordinary roads not specified by signs or markings is 60 kilometers per hour',
        '驾驶座席靠背的位置应调整到双手握方向盘时，肘部微曲的状态相一致': 'The position of the driver\'s seat backrest should be adjusted to match the state where the elbows are slightly bent when holding the steering wheel with both hands',
        '要改变车道时，因后方有车辆已接近，所以没有改变车道让了路': 'When wanting to change lanes, because a vehicle was approaching from behind, I did not change lanes and yielded',
        '因贴有初学者标记的汽车以最高限速以下的速度行驶，所以鸣笛让对方避到道路左侧后驶了过去': 'Because a car with a beginner\'s mark was driving below the maximum speed limit, I honked to make it move to the left side of the road and then passed',
        '让儿童坐在前面的座席不仅对儿童非常危险，也影响驾驶操作': 'Having children sit in the front seat is not only very dangerous for children but also affects driving operation',
        '因为在没有人行横道的交叉路有行人横过，为不妨碍其通行，暂时停了下来等待行人横过结束': 'Because there were pedestrians crossing at an intersection without a pedestrian crossing, I temporarily stopped to wait for the pedestrians to finish crossing so as not to obstruct their passage',
        '路面被雨水淋湿、轮胎磨损严重时，与干燥路面轮胎状况良好时相比，停车距离基本没有差别': 'When the road surface is wet from rain and tires are severely worn, compared to when the road surface is dry and tire conditions are good, the stopping distance is basically no different',
        '不能进入有该标示的路侧带内驻车或停车': 'You cannot enter and park or stop within the roadside strip marked with this sign',
        '禁止在上坡的坡顶附近及陡下坡超越汽车及轻型摩托车': 'Overtaking cars and light motorcycles is prohibited near the top of an uphill slope and on steep downhill slopes',
        '红灯闪烁时，面对该信号的车辆及有轨电车，要在停车位置暂时停车，确认安全后可以前行': 'When the red light flashes, vehicles and streetcars facing this signal must temporarily stop at the stopping position, and can proceed after confirming safety',
        '无论道路状况或其它交通状况如何，都禁止越入道路中心以右的部分通行': 'Regardless of road conditions or other traffic conditions, it is prohibited to cross into the right side of the road center',
        '根据标志要暂时停车的交叉路是容易发生交通事故的危险场所，因此必须暂时停车确认安全后再通行': 'Intersections where temporary stops are required by signs are dangerous places prone to traffic accidents, so you must temporarily stop and confirm safety before proceeding',
        '在停止着的幼儿园、学校班车旁边通过时，必须暂时停车确认安全': 'When passing beside a stopped kindergarten or school bus, you must temporarily stop and confirm safety',
        '所谓超车，是指改变车道驶到前面正在行驶的车辆的前方，因为驾驶操作复杂，所以尽量不要超车，以安全的速度行驶': 'Overtaking means changing lanes to get in front of a vehicle ahead. Because the driving operation is complex, it is best to avoid overtaking and drive at a safe speed',
        '儿童安全椅在生病等不得已的情况下可以不使用': 'Child safety seats can be omitted in unavoidable circumstances such as illness',
        # 第二批翻译规则
        '该标志表示是道路的中心或中心线': 'This sign indicates the center or centerline of the road',
        '在交叉路内，发现从后方有紧急车辆接近时，必须立即原地停车': 'When inside an intersection, if you discover an emergency vehicle approaching from behind, you must immediately stop where you are',
        '因为前方的信号从黄色变成了红色，所以为提醒后面驶来的车辆停车分数次踩了刹车': 'Because the signal ahead changed from yellow to red, I tapped the brakes several times to alert the vehicle behind to stop',
        '左右转弯等行为结束时，收回所发出信号的时间是其行为结束的约3秒钟之后': 'When finishing actions such as turning left or right, the time to retract the signal is about 3 seconds after the action ends',
        '取得普通临时驾驶执照的人，如果是为了练习，可以驾驶轻型摩托车': 'A person who has obtained an ordinary temporary driver\'s license can drive a light motorcycle if it is for practice',
        '腰部安全带松弛地系在腹部即可': 'The lap belt should be fastened loosely around the abdomen',
        '该标志是表示注意危险的警告标志': 'This is a warning sign indicating danger ahead',
        '在设有公共汽车等优先通行带的道路上，为了向左转弯通过了该车辆通行带': 'On a road with a priority lane for buses, I crossed the lane to make a left turn',
        '汽车驾驶员在有行人的安全地带旁边通过时必须缓行': 'Car drivers must drive slowly when passing beside pedestrian safety zones',
        '驾驶汽车时不得随意改变车道，但在不得已的情况下改变车道时，需要利用后视镜或通过目视来确认安全': 'When driving a car, you must not change lanes arbitrarily, but when changing lanes in unavoidable circumstances, you need to use the rearview mirror or visually confirm safety',
        '因为自动变速车的基本要领是操作加速踏板和刹车踏板，所以不必特别注意变速杆的操作': 'Because the basic technique for automatic transmission vehicles is to operate the accelerator and brake pedals, there is no need to pay special attention to gear lever operation',
        '该标志指禁止车辆进入，不能从有标志的方向进入': 'This sign indicates no entry for vehicles, and entry from the direction of the sign is prohibited',
        '在没有车辆通行带的道路上，除了超车等不得已的情况以外，要靠道路的左侧通行': 'On roads without vehicle lanes, except in unavoidable circumstances such as overtaking, you should drive on the left side of the road',
        '通过铁路道内时，为了防止发动机熄火，最好尽早变速一气通过': 'When crossing a railroad crossing, it is best to shift gears early and pass through in one go to prevent engine stalling',
        '汽车驾驶员不得做产生较大噪音等明显给他人带来麻烦的急起动、急加速及空转': 'Car drivers must not perform sudden starts, sudden acceleration, or idling that creates loud noise and clearly causes trouble to others',
        '超车时，首先要边向右侧靠近边打开右侧方向指示灯，其次最好用眼睛确认后方的安全': 'When overtaking, first move to the right side while turning on the right turn signal, then it is best to visually confirm safety behind',
        '不得向即将驾驶的人敬酒或劝酒': 'You must not toast or encourage drinking to someone who is about to drive',
        '该标志表示路基容易塌落，需要注意': 'This sign indicates that the roadbed is prone to collapse and caution is needed',
        '因为停在车站的公共汽车通过方向指示灯等发出了起动信号，所以缓行让公共汽车先起动了': 'Because the bus stopped at the station gave a start signal through the turn signal, I slowed down to let the bus start first',
        '在上坡的坡顶附近及陡下坡处必须缓行': 'You must drive slowly near the top of an uphill slope and on steep downhill slopes',
        '超越前面的车辆时，必须鸣笛引起对方注意后超车': 'When overtaking the vehicle ahead, you must sound the horn to alert it and then overtake',
        '装有防锁死刹车系统的车辆急刹车时，如果不一气用力踩下刹车并一直踩住的话，系统就不动作': 'When emergency braking in a vehicle equipped with an anti-lock braking system, if you do not press the brake firmly and hold it down, the system will not work',
        '该标志为禁止右转弯的标志': 'This is a no right turn sign',
        '汽车和轻型摩托车除了为进出面向道路的场所而横过以外，不得在人行道、路侧带及自行车道等处通行': 'Cars and light motorcycles must not travel on sidewalks, roadside strips, or bicycle lanes except when crossing to enter or exit road-facing places',
        '驾驶汽车时，不得超过标志或标示所示的最高限速行驶': 'When driving a car, you must not exceed the maximum speed limit shown by signs or markings',
        '在上车之前，如果确认了车前后是否有人，就没有必要连汽车的下面也确认': 'Before getting in the car, if you confirm whether there are people in front and behind the car, there is no need to check under the car',
        '被其它车辆超车时，如果没有充分的余地超越对方，必须尽量靠向左侧让路': 'When being overtaken by other vehicles, if there is not sufficient room to overtake, you must move as far to the left as possible to yield',
        '驾驶员必须锁上汽车的安全栓，以免同乘者无意中打开车门': 'Drivers must lock the car\'s safety lock to prevent passengers from accidentally opening the door',
        '在有该标志的地方，总排气量在125cc以下的普通二轮摩托车不能通行': 'Where this sign is present, ordinary motorcycles with a total displacement of 125cc or less cannot pass',
        '即使警察署和消防署等前面标有禁止停车部分的标示，因为是紧急情况时的标示，所以，除了紧急情况以外，可以进入标示部分停车': 'Even if there are no-parking markings in front of police stations and fire stations, because these are for emergency situations, you can enter and park in the marked area except during emergencies',
        '在雪地驾驶时，由于停车距离比在干燥的柏油路要长，所以必须时常控制速度小心驾驶': 'When driving on snow, because the stopping distance is longer than on dry asphalt, you must constantly control speed and drive carefully',
        '右转弯或左转弯发出信号的时间是其行为开始大约3秒之前': 'The time to signal for a right or left turn is about 3 seconds before the action begins',
        '用大型特殊驾驶执照可以驾驶大型特殊汽车、小型特殊汽车及轻型摩托车': 'With a large special driver\'s license, you can drive large special vehicles, small special vehicles, and light motorcycles',
        '在驾驶途中因有急事打车载电话或手机时，最好将车停靠在道路的左端后再打': 'When making a car phone or mobile phone call while driving due to an emergency, it is best to pull over to the left side of the road before making the call',
        '该标示表示是自行车横道': 'This marking indicates a bicycle crossing',
        '在交叉路近前用黄线划有车辆通行带的地方，不能向指定以外的方向改变车道': 'At places near intersections where vehicle lanes are marked with yellow lines, you cannot change lanes in directions other than those specified',
        '即使标志等指定的最高限速为时速20公里，在交通量少的时候，也可以超过该速度驾驶': 'Even if signs specify a maximum speed limit of 20 kilometers per hour, when traffic is light, you can drive faster than that speed',
        '接近人行横道时，除了明显没有行人及自行车横过的情况以外，必须以能够在其近前停车的速度行驶': 'When approaching a pedestrian crossing, except when there are obviously no pedestrians or bicycles crossing, you must drive at a speed at which you can stop before it',
        '即使是在用黄线划分的车辆通行带，只要后面没有车辆，就可以越过黄线改变车道': 'Even in vehicle lanes marked with yellow lines, as long as there are no vehicles behind, you can cross the yellow line to change lanes',
        '自动变速车的变速杆在P档或N档的位置时，由于溜车现象，有可能使车辆滑动': 'When an automatic transmission vehicle\'s gear lever is in P or N position, due to the rolling phenomenon, the vehicle may slide',
        '不得突然加塞到其它车辆的前面及贴挤并行车辆': 'You must not suddenly cut in front of other vehicles or squeeze alongside parallel vehicles',
        '驾驶自动变速车时，如果停止时间可能较长，最好将变速杆切入N档，并使用手刹': 'When driving an automatic transmission vehicle, if the stop time may be long, it is best to shift to N gear and use the hand brake',
        '即使车辆是为了进出面向道路的场所，也不能横穿人行道和路侧带': 'Even if a vehicle is for entering or exiting a road-facing place, it cannot cross sidewalks and roadside strips',
        '驾驶员坐在驾驶座席上看车外时，视线被车身等妨碍，有看不到的部分，将看不到的部分称为死角': 'When a driver sits in the driver\'s seat and looks outside, vision is obstructed by the vehicle body, creating blind spots',
        '其它车辆准备超车时，在对方没有充分的余地超车的情况下，不需要特意让路': 'When other vehicles are preparing to overtake, if the other party does not have sufficient room to overtake, there is no need to specifically yield',
        '不得醉酒后在道路上蹒跚行走或站着聊天等妨碍交通': 'You must not stagger or stand and chat on the road while drunk, obstructing traffic',
        '该标志表示两条道路合流，道路变宽': 'This sign indicates two roads merging and the road widening',
        '有紧急车辆接近，但因不在交叉路附近，所以靠道路的左侧让了路': 'An emergency vehicle was approaching, but because it was not near an intersection, I moved to the left side of the road to yield',
        '高明的刹车方法是不过度地使用制动器，尽量操作加速器慢慢地减速后停车': 'A skillful braking method is to not overuse the brake, but rather operate the accelerator to gradually slow down and then stop',
        '发出错误或不必要的信号，会使其它交通困惑，危险增加': 'Giving wrong or unnecessary signals will confuse other traffic and increase danger',
        '该标志表示是专为行人通行而设的道路': 'This sign indicates a road dedicated for pedestrian use',
        '在交叉路和人行横道之前所表示的停车线只是车辆大概的停车位置，因此不用太在意停车线': 'The stop line shown before intersections and pedestrian crossings is only an approximate stopping position for vehicles, so you don\'t need to pay too much attention to it',
        '由于河川涨水处于危险状态，警察禁止在桥上通行，但因为不是标志所示的禁止通行，所以无视警察的指示从桥上驶了过去': 'Due to dangerous flooding, police prohibited passage on the bridge, but because it was not a sign-prohibited passage, I ignored the police instruction and drove across the bridge',
        '卷入事故是指驾驶车辆左转弯时，将行人或自行车等卷入车辆的左后部轮胎或保险杠内的事故': 'An entrapment accident refers to an accident where a pedestrian or bicycle is caught in the left rear tire or bumper of a vehicle when turning left',
        '在一个人行走的儿童旁边通过时，必须暂时停车，让其安全通行': 'When passing beside a child walking alone, you must temporarily stop to allow safe passage',
        '临时驾驶执照是指要取得第一种驾驶执照或第二种驾驶执照的人为了练习等而驾驶大型汽车、中型汽车或普通汽车时的驾驶执照': 'A temporary driver\'s license is a license for those seeking a Class 1 or Class 2 driver\'s license to drive large, medium, or ordinary vehicles for practice',
        '该标志表示禁止大型二轮摩托车、普通二轮摩托车及轻型摩托车通行': 'This sign prohibits passage of large motorcycles, ordinary motorcycles, and light motorcycles',
        '以比其它车辆慢的速度行驶时，应尽量靠道路的左侧行驶，以免影响交通畅通': 'When driving slower than other vehicles, you should drive as far to the left as possible to avoid affecting traffic flow',
        '通过铁路道时，为避免车轮陷入路边的铁轨里，应稍稍靠近道路中心通行': 'When passing through a railroad crossing, to avoid wheels getting stuck in the tracks, you should pass slightly closer to the center of the road',
        '如果是在所规定的速度范围内，就可以反复地进行急起动、急加速': 'If within the specified speed range, you can repeatedly perform sudden starts and sudden acceleration',
        '想要超车时，首先必须确认该场所不是禁止超车的场所': 'When wanting to overtake, you must first confirm that the location is not a prohibited overtaking area',
        '由于自己没有驾驶执照，虽然知道朋友已经喝了酒，但还是求朋友开车将自己送到了家里': 'Because I don\'t have a driver\'s license, even though I knew my friend had been drinking, I still asked my friend to drive me home',
        '在有该标志的道路上，表示前方的路面不平': 'On roads with this sign, it indicates that the road surface ahead is uneven',
        '虽然公共汽车发出了信号起动了，但鸣笛后紧跟着前方车辆超越了公共汽车': 'Although the bus gave a signal and started, I honked and then immediately followed the vehicle ahead to overtake the bus',
        '车辆总重量不满5,000kg、最大载重量不满3,000kg的货车用普通驾驶执照即可驾驶': 'Trucks with a total vehicle weight of less than 5,000kg and maximum load capacity of less than 3,000kg can be driven with an ordinary driver\'s license',
        '在住宅区行驶时，因为接近视野不好的小巷，所以鸣笛驶了过去': 'When driving in a residential area, because I was approaching a narrow alley with poor visibility, I honked and passed',
        '自动变速车在上坡驻车时，要在踩住刹车踏板并拉住手刹后将变速杆切入P档': 'When parking an automatic transmission vehicle on an uphill slope, you should shift to P gear after pressing the brake pedal and pulling the hand brake',
        '该图所示的警察的手势信号对于箭头方向的交通而言，与红灯信号含义相同': 'The police officer\'s hand signal shown in the figure has the same meaning as a red light signal for traffic in the arrow direction',
        '即使可以越入道路中心以右的部分通行，除了单行路以外，也必须尽量减少越入道路右侧的次数': 'Even if you can cross into the right side of the road center, except on one-way roads, you must minimize the number of times you cross into the right side of the road',
        '在根据标志或标示指定要暂时停车的交叉路，如果没有其它车辆而且没有特别危险时，不需暂时停车': 'At intersections where temporary stops are required by signs or markings, if there are no other vehicles and no particular danger, temporary stops are not necessary',
        '初学驾驶员（取得普通驾驶执照未经过1年者）驾驶从别人那里借来的普通汽车时，不用贴「初学者标记」': 'Beginner drivers (those who have held an ordinary driver\'s license for less than 1 year) do not need to display a "beginner mark" when driving an ordinary car borrowed from someone else',
        '超车时，如果对前方车辆的行动或前方的交通等多少有一些不安，最好毫不犹豫地一气超过去': 'When overtaking, if you have any concerns about the actions of the vehicle ahead or the traffic ahead, it is best to overtake decisively without hesitation',
        '腰部安全带要勒紧髋部，并确认安全带是否扭曲': 'The lap belt should be tightened around the hips, and you should confirm whether the belt is twisted',
        '该标示表示此场所为「禁止掉头」的终点': 'This marking indicates that this location is the end of a "no U-turn" section',
        '在公共汽车等优先通行带行驶时，虽然幼儿园班车接近，但由于不是公共汽车，所以照常行驶了': 'When driving in a priority lane for buses, although a kindergarten bus approached, because it was not a bus, I continued driving as usual',
        '如果与停止着的有轨电车的侧面间隔在1.5米以上，无论是否有人上下车都可以注意通过': 'If the side distance from a stopped streetcar is 1.5 meters or more, you can pass with caution regardless of whether people are getting on or off',
        '在等信号停车时突然想起有急事而使用了手机，但因为对面的信号变绿了，所以边说话边起动了': 'While waiting at a signal, I suddenly remembered something urgent and used my phone, but because the opposite signal turned green, I started while talking',
        '该标示表示前方有人行横道或自行车横道': 'This marking indicates a pedestrian crossing or bicycle crossing ahead',
        '在用标志或标示指定为直行或左转弯等通行方向的交叉路，必须按所指定的方向行进': 'At intersections where signs or markings specify directions such as straight or left turn, you must proceed in the specified direction',
        '因为有行人想横过人行横道所以暂时停了车，但由于有急事，鸣笛提醒行人注意后，比行人先行通过了': 'Because a pedestrian wanted to cross the pedestrian crossing, I temporarily stopped, but due to an emergency, I honked to alert the pedestrian and then passed before the pedestrian',
        '即使是在前方车辆准备超越其前面的汽车时，只要能够确认前方的安全就可以超越这些车辆': 'Even when the vehicle ahead is preparing to overtake the car in front of it, as long as you can confirm safety ahead, you can overtake these vehicles',
        '在交叉路跟着前面的车右转弯时，如果前面的车已经发出信号的话，就不必发出右转弯的信号': 'When following the vehicle ahead to turn right at an intersection, if the vehicle ahead has already signaled, you don\'t need to signal a right turn',
        '该标志表示不得以超过时速50公里的速度行驶': 'This sign indicates that you must not drive at speeds exceeding 50 kilometers per hour',
        '在为进出面向道路的场所而横过路侧带时，如有行人应缓行通过': 'When crossing a roadside strip to enter or exit a road-facing place, if there are pedestrians, you should pass slowly',
        '驾驶员感觉到危险后刹车到制动器实际开始起作用之间的车辆行驶距离称为空走距离': 'The distance a vehicle travels from when the driver senses danger and brakes until the brake actually starts to work is called the free-running distance',
        '如果发出起车信号之前确认了前后左右安全的话，发出信号后，就不必再次确认安全': 'If you confirmed safety in all directions before giving the start signal, after giving the signal, you don\'t need to confirm safety again',
        '在行驶方向的前方有障碍物时，要提前暂时停车或减速，让对面驶来的车辆先通行': 'When there is an obstacle ahead in the direction of travel, you should temporarily stop or slow down in advance to let oncoming vehicles pass first',
        '正确地使用儿童安全椅，在发生交通事故时可以大大地减少伤害，同时可以防止儿童妨碍驾驶': 'Using a child safety seat correctly can greatly reduce injuries in traffic accidents and prevent children from interfering with driving',
        '该标示表示是禁止入内部分': 'This marking indicates a no-entry area',
        '打算在前方交叉路左转弯时，必须在临左转弯之前靠向道路的左端左转弯': 'When planning to turn left at an intersection ahead, you must move to the left end of the road just before turning left',
        '在停止的车辆旁通过时，不必连车内是否有人也注意': 'When passing beside a stopped vehicle, you don\'t need to pay attention to whether there are people inside',
        '因为车辆横穿、掉头、倒车是妨碍交通顺畅的驾驶行为，所以必须充分注意不要妨碍行人和其它车辆的正常通行': 'Because crossing, U-turning, and reversing are driving behaviors that obstruct smooth traffic, you must pay full attention not to obstruct the normal passage of pedestrians and other vehicles',
        '自动变速车的发动机刚起动时，因为发动机的转数升高，所以不踩紧刹车踏板操作会有急起动的危险': 'When an automatic transmission vehicle\'s engine first starts, because the engine RPM increases, operating without firmly pressing the brake pedal can cause sudden starting',
        '警察用手势信号指挥交通时必须遵守，但由于交通巡查员不是警察，所以不遵守其手势信号也行': 'You must obey police hand signals when directing traffic, but because traffic inspectors are not police, you don\'t have to obey their hand signals',
        '只有在没有自行车通行的情况下，轻型摩托车才可以在自行车道通行': 'Light motorcycles can only travel on bicycle lanes when there is no bicycle traffic',
        '在交叉路左转弯时，应该充分注意靠向左侧通行的二轮摩托车，提前靠近道路的左端缓行，以免发生卷入事故': 'When turning left at an intersection, you should pay full attention to motorcycles traveling on the left, approach the left end of the road early and drive slowly to avoid entrapment accidents',
        '看到儿童在道路上玩时，只要鸣笛警告就可以不用缓行通过': 'When seeing children playing on the road, you can pass without slowing down as long as you honk to warn them',
        '在没有车辆通行带的隧道，不得为超越汽车或轻型摩托车改变车道或在其车辆旁边通过': 'In tunnels without vehicle lanes, you must not change lanes or pass beside vehicles to overtake cars or light motorcycles',
        '发生交通事故时，刑事责任由驾驶员承担，但民事责任全部由所加入的保险公司承担': 'When a traffic accident occurs, criminal responsibility is borne by the driver, but all civil liability is borne by the insurance company',
        # 第三批翻译规则
        '即使是在有最高时速40公里标志的路段行驶，轻型摩托车的时速也不得超过30公里': 'Even when driving on a road section with a maximum speed sign of 40 kilometers per hour, light motorcycles must not exceed 30 kilometers per hour',
        '开车时在行人旁边通过时，必须缓行保证行人安全': 'When driving and passing beside pedestrians, you must drive slowly to ensure pedestrian safety',
        '在安全地带的旁边通过时，只在有行人时缓行就可以了': 'When passing beside a safety zone, you only need to drive slowly when there are pedestrians',
        '从停车的机动车旁边通过时，有时车门会突然打开，或者突然从车后冲出行人，必须减速谨慎通行': 'When passing beside a parked motor vehicle, doors may suddenly open or pedestrians may suddenly rush out from behind the vehicle, so you must slow down and proceed with caution',
        '从正在上下车的学校、幼儿园校车旁边通过时，必须暂时停车确认安全': 'When passing beside a school or kindergarten bus where people are getting on or off, you must temporarily stop and confirm safety',
        '对于贴有此图标的车，因为危险，禁止超车和追车': 'For vehicles displaying this icon, because it is dangerous, overtaking and chasing are prohibited',
        '准备在交叉路左转弯时，必须在转弯前约3秒钟发出左转弯的信号': 'When preparing to turn left at an intersection, you must signal a left turn about 3 seconds before turning',
        '改变车道、掉头、倒车等行为结束时，必须在经过约3秒钟之后取消该信号': 'When finishing actions such as changing lanes, U-turning, or reversing, you must cancel the signal after about 3 seconds',
        '即使是在用黄线划分车道通行带的地方，如果是为了左右转弯，就可以越过该线改变车道': 'Even in places where lanes are marked with yellow lines, if it is for turning left or right, you can cross the line to change lanes',
        '在坡度大的下坡禁止超车，但是在坡度大的上坡不禁止超车': 'Overtaking is prohibited on steep downhill slopes, but not prohibited on steep uphill slopes',
        '交叉路及其跟前30米以内的场所，不能超车，但是在优先道路上行驶时可以超车': 'You cannot overtake at intersections and within 30 meters before them, but you can overtake when driving on priority roads',
        '在有图中标志的地方不能超车': 'You cannot overtake at places with the sign shown in the figure',
        '在视线较好的铁路道，如果可以确认安全，则可以缓行通过': 'At railroad crossings with good visibility, if you can confirm safety, you can pass slowly',
        '为紧急车辆让行时，即使在单行线上，也必须将车辆靠向道路左侧': 'When yielding to emergency vehicles, even on a one-way road, you must move the vehicle to the left side of the road',
        '在设有公交车等专用车道的道路上，车辆（小型特殊机动车、轻型摩托车、轻型车辆），除在转弯等不得已的情况外，不可在该车道行驶': 'On roads with dedicated lanes for buses, vehicles (small special motor vehicles, light motorcycles, light vehicles) cannot travel in that lane except in unavoidable circumstances such as turning',
        '在交叉路按指定机动汽车道路行驶，即使有紧急车辆接近也可以不必让行': 'When driving on a designated motor vehicle road at an intersection, you do not need to yield even if an emergency vehicle approaches',
        '在前车要转弯、发出改变车道的信号时，除非必须急刹车或急打方向盘的情况外，不得妨碍其改变车道': 'When the vehicle ahead wants to turn and signals a lane change, you must not obstruct its lane change unless you must brake suddenly or turn the steering wheel suddenly',
        '腰部安全带如系在腹部而非腰部位置，一旦发生事故会受到强力压迫有危险，因此应该系在盆骨部位': 'If the lap belt is fastened around the abdomen rather than the waist, it can cause strong compression in an accident, so it should be fastened around the pelvic area',
        '乘坐副驾驶座位的人必须使用安全带，但坐在后部座位的人不必使用': 'People sitting in the front passenger seat must use seat belts, but those sitting in the rear seats do not need to',
        '在如图所示道路上，A车超B车时，不得超出中央线在右侧部分行驶': 'On the road shown in the figure, when vehicle A overtakes vehicle B, it must not cross the center line to drive on the right side',
        '同一方向有三条车道行驶带时，最右侧为超车用通行带，应让开行驶，车速慢的在左侧通行带行驶，车速快的在右侧通行带行驶': 'When there are three lanes in the same direction, the rightmost lane is for overtaking and should be kept clear. Slow vehicles drive in the left lane, fast vehicles drive in the right lane',
        '在不得已的情况下，可以在安全地带行驶': 'In unavoidable circumstances, you can drive in a safety zone',
        '在图中表示的地方，不越过右侧道路部分的时候可以超车': 'At the place shown in the figure, you can overtake without crossing into the right side of the road',
        '有图中的车辆通行带的地方,可以按箭头指向改变车道': 'At places with vehicle lanes shown in the figure, you can change lanes according to the arrow direction',
        '图中的交叉路,属于 A 车一侧和 B 车一侧的视线都较差的交叉路,因此 A 和 B 车都必须缓行': 'The intersection shown in the figure is one where visibility is poor on both vehicle A\'s side and vehicle B\'s side, so both vehicles A and B must drive slowly',
        '图示禁止车辆进入，车辆可以从标志的对面(背面)进入,但是不得从正面通行': 'The figure shows no entry for vehicles. Vehicles can enter from the opposite (back) side of the sign, but must not pass from the front',
        '自动车的乘坐定员时，12 岁未满的孩子 2 人可以算作大人 1 人': 'For vehicle passenger capacity, 2 children under 12 years old can be counted as 1 adult',
        '持有普通驾驶执照的人,除可以驾驶普通机动车以外，还可以驾驶小型的特殊机动车和轻型摩托车': 'A person holding an ordinary driver\'s license can drive not only ordinary motor vehicles but also small special motor vehicles and light motorcycles',
        '再雪地或结冰的道路等行驶的时候,必须使用轮胎防滑链或者冬季轮胎，防备打滑或者横向打滑等': 'When driving on snowy or icy roads, you must use tire chains or winter tires to prevent slipping or sideways skidding',
        '停在道路左侧的车辆起步时的信号,可以按与向右改变车道时相同的要领发出': 'The signal when starting a vehicle parked on the left side of the road can be given in the same way as when changing lanes to the right',
        '自动变速车在启动发动机的时候,在启动发动机前要脚踏刹车踏板确定位置，用眼睛确认油门踏板位置等非常重要': 'When starting an automatic transmission vehicle, it is very important to press the brake pedal to confirm position before starting the engine and visually confirm the accelerator pedal position',
        '进行摩托车的刹车操作时，不要打方向盘,使车体保持笔,同时使用前后轮制动器': 'When braking a motorcycle, do not turn the steering wheel, keep the body straight, and use both front and rear wheel brakes',
        '改变车道的时候,如果后面的车不能避免急刹车或者急打方向盘的情况下,就不能改变车道': 'When changing lanes, if the vehicle behind cannot avoid sudden braking or sudden steering, you cannot change lanes',
        '在靠着道路左侧步行道与步行道平行停着的车辆右侧不可以停泊车，但是可以临时停车': 'You cannot park on the right side of a vehicle parked parallel to the sidewalk on the left side of the road, but you can temporarily stop',
        '夜间与白天相比视野比较差,看不清行人和自行车等,会导致发现得太晚,所以行驶速度应该比白天慢': 'At night, visibility is worse than during the day, making it hard to see pedestrians and bicycles, which can lead to late detection, so driving speed should be slower than during the day',
        '两人同乘大型摩托车或普通摩托车等的时候,应该尽可能选择后部位置较为宽敞的车型': 'When two people ride together on a large motorcycle or ordinary motorcycle, you should choose a model with a more spacious rear seat if possible',
        '即使获得了普通摩托车驾驶执照,获得期间未满 1 年的人,在一般道路上不能带人驾驶普通摩托车': 'Even if you have obtained an ordinary motorcycle license, a person who has held it for less than 1 year cannot carry passengers when driving an ordinary motorcycle on ordinary roads',
        '准备在高速公路上通行时,为了避免由于燃料冷却水、发动机油不足而停止.必须特意检查': 'When preparing to travel on the expressway, to avoid stopping due to insufficient fuel, coolant, or engine oil, you must specifically check',
        '用吊车吊起故障车的前轮或后轮牵引时，不需要驾驶员坐在故障车里': 'When towing a broken-down vehicle by lifting the front or rear wheels with a crane, the driver does not need to sit in the broken-down vehicle',
        '踩刹车的时候，感觉到比较松弛的时候，说明刹车很起作用': 'When stepping on the brake, if it feels relatively loose, it means the brake is working well',
        '高速道路中微型汽车、轻型摩托车发动机的总排气量在 125cc 以下的车辆禁止通行': 'On expressways, vehicles with micro cars and light motorcycles with total engine displacement of 125cc or less are prohibited',
        '检查证是很重要的资料,所以应该准备一份复印件放在车里备用，将原件好好保存': 'The inspection certificate is very important, so you should prepare a copy to keep in the car and store the original safely',
        '车辆在有行人在旁边通过时，必须缓行保证行人安全': 'When a vehicle passes beside pedestrians, it must drive slowly to ensure pedestrian safety',
        '安全地带的左侧和它前后 10 米以内的场所虽然不能停,自车，但是可以临时停车': 'Although you cannot park on the left side of a safety zone and within 10 meters before and after it, you can temporarily stop',
        '行入专用道路,准许小型特殊机动车,轻型摩托车及轻型车通行': 'Pedestrian-only roads permit small special motor vehicles, light motorcycles, and light vehicles to pass',
        '为紧急车辆让行时,即使在单行线上，也必须将车辆靠向道路左侧': 'When yielding to emergency vehicles, even on a one-way road, you must move the vehicle to the left side of the road',
        '在左侧部分的路面宽度在 6 米以上的道路,视线良好并且不会影响对面驶来的车的通行时，可以从道路右侧越线超车': 'On roads where the left side has a width of 6 meters or more, when visibility is good and it will not affect oncoming traffic, you can cross the line from the right side of the road to overtake',
        '在有步行道的道路上停车的时候,为了留出更宽的车道,最好将轮胎的一部分停在步行道上': 'When parking on a road with a sidewalk, to leave a wider lane, it is best to park part of the tire on the sidewalk',
        '在高速公路上准备从加速车道驶入干线车道时,必须注意后方驶来的车辆,而不是在干线车道上行驶的前方车辆': 'When preparing to enter the main lane from the acceleration lane on the expressway, you must pay attention to vehicles approaching from behind, not vehicles ahead in the main lane',
        '前面或出入前后 3 米以内的场所,如果是自己所拥有的车库或就可以停泊车': 'Places within 3 meters before or after entrances and exits, if it is your own garage, you can park',
        '由于安全带在发生交通事故时可以大大地减少伤害，驾驶后排座位有安全带的车的驾驶员让后排的同乘者也系上了安全带': 'Because seat belts can greatly reduce injuries in traffic accidents, a driver of a car with rear seat belts had rear passengers also fasten their seat belts',
        '该标志指不仅是车辆，有轨电车和行人等都禁止通行': 'This sign indicates that not only vehicles but also streetcars and pedestrians are prohibited',
        '刹车时，一开始就要尽量用力踩下去为好': 'When braking, it is best to press down as hard as possible from the start',
        '准备掉头或向右转弯时，必须在到达距其行为开始的地点的30米之前的地点时发出信号': 'When preparing to make a U-turn or turn right, you must signal when you reach a point 30 meters before where the action begins',
        '取得第一种普通驾驶执照的人，即便是为了将出租车送回修理工场，也不可以驾驶': 'A person holding a Class 1 ordinary driver\'s license cannot drive even for the purpose of returning a taxi to a repair shop',
        '该标示表示禁止进入其内停车': 'This marking indicates that entry and parking inside are prohibited',
        '由于交叉路及其附近是交通事故的多发场所，因此应该提速迅速地通过': 'Because intersections and their vicinity are places where traffic accidents frequently occur, you should speed up and pass quickly',
        '只要取得普通驾驶执照，就可以驾驶最大载重量为4,000kg的货车和乘车定员为11大的乘用汽车': 'As long as you have an ordinary driver\'s license, you can drive trucks with a maximum load capacity of 4,000kg and passenger cars with a capacity of 11 people',
        '驾驶员不仅需要掌握驾驶技术及知识，作为社会一员，对其他的道路利用者还需要有体谅的心态': 'Drivers not only need to master driving skills and knowledge, but as members of society, they also need to have a considerate attitude toward other road users',
        '该标志表示车辆可以直行及左转弯，但不能右转弯': 'This sign indicates that vehicles can go straight and turn left, but cannot turn right',
        '车辆不能在轨道线内通行，但右转弯、左转弯、横过、掉头等时可以在轨道线内横过': 'Vehicles cannot travel within the track lines, but can cross within the track lines when turning right, turning left, crossing, or making a U-turn',
        '驾驶员感觉到危险踩刹车时，从制动开始起作用到车辆停止的距离称为停车距离': 'When a driver senses danger and brakes, the distance from when the brake starts to work until the vehicle stops is called the stopping distance',
        '在后方视野不好的场所或从狭窄的道路驶到宽阔道路等不得已倒车起动时，最好让同乘者帮助确认后方': 'When starting in reverse in unavoidable circumstances such as places with poor rear visibility or when moving from a narrow road to a wide road, it is best to have a passenger help confirm the rear',
        '在有障碍物的场所错车时，向有障碍物方向行驶的车辆可以优先通行': 'When passing at a place with obstacles, the vehicle traveling toward the obstacle has priority',
        '在有该标志的地方，因为有交叉路，所以必须鸣笛通行': 'At places with this sign, because there is an intersection, you must sound the horn when passing',
        '即使是在没有交通指示而且视野不好的交叉路，只要没有其它车辆就可以不用缓行通过': 'Even at intersections without traffic signals and with poor visibility, as long as there are no other vehicles, you can pass without slowing down',
        '取得临时驾驶执照的人如果在汽车所规定的位置上贴上临时驾驶执照练习标记，就可以为了练习而一个人驾驶': 'A person with a temporary driver\'s license can drive alone for practice if they display a temporary license practice mark in the position specified for the vehicle',
        '原则上，车辆应该在道路中心（有中心线时，为中心线）以左的部分通行': 'In principle, vehicles should travel on the left side of the road center (or center line if there is one)',
        '上车后关车门时，为了防止车门没关紧，最好用力一下关好': 'When closing the car door after getting in, to prevent the door from not closing properly, it is best to close it firmly with force',
        '取得中型驾驶执照的人可以驾驶乘车定员为30人的巴士': 'A person holding a medium driver\'s license can drive a bus with a capacity of 30 people',
        '该标志下的辅助标牌表示上述主标志的交通限制地段': 'The auxiliary sign under this sign indicates the traffic restriction area of the main sign above',
        '在道路左侧被指定为公共汽车专用通行带的地方，即使是左转弯时，也不能在该车道通行': 'At places where the left side of the road is designated as a dedicated bus lane, even when turning left, you cannot travel in that lane',
        '在自动变速车使用发动机制动时，最好将变速杆切入2档或L档(或1档)': 'When using engine braking in an automatic transmission vehicle, it is best to shift to 2nd gear or L gear (or 1st gear)',
        '在行人旁边通过时必须与行人之间留出充分的间隔或缓行，但行人在路侧带时则没有必要': 'When passing beside pedestrians, you must leave sufficient space or drive slowly, but this is not necessary when pedestrians are in the roadside strip',
        '即使前方信号灯的信号是红色，也必须听从正在指挥交通的警察的右转弯或左转弯的指示': 'Even if the signal ahead is red, you must follow the police officer directing traffic\'s instruction to turn right or left',
        '道路中心线的左侧部分正在施工不能通行时，可以越入右侧部分通行': 'When the left side of the road center line is under construction and cannot be used, you can cross into the right side to pass',
        '由于铁路道对面交通拥挤，若照常行驶有可能在铁路道内停滞不动时，不得进入铁路道': 'Because traffic is congested on the opposite side of the railroad crossing, if normal driving might cause you to stall in the crossing, you must not enter the railroad crossing',
        '超车时，如果急加速或急打方向盘改变车道，就有可能导致方向盘失控或发生侧滑，所以必须充分注意': 'When overtaking, if you accelerate suddenly or turn the steering wheel suddenly to change lanes, it may cause loss of steering control or side skidding, so you must pay full attention',
        '该标志表示前方道路是上陡坡': 'This sign indicates that the road ahead is a steep uphill slope',
        '右转弯时，必须尽量提前靠近道路的中心，紧贴交叉路中心的内侧（根据标志指定有通行场所时，在其指定的场所）缓行': 'When turning right, you must approach the center of the road as early as possible and drive slowly close to the inner side of the intersection center (or at the place specified by signs if applicable)',
        '在为起动自动变速车而操作变速杆时，只要不松开加速踏板，就不用拉手刹或踩刹车踏板': 'When operating the gear lever to start an automatic transmission vehicle, as long as you don\'t release the accelerator pedal, you don\'t need to pull the hand brake or press the brake pedal',
        '在根据标志或标示禁止横穿或掉头的地点，即使没有行人或其它车辆也不得横穿或掉头': 'At places where crossing or U-turning is prohibited by signs or markings, you must not cross or make a U-turn even if there are no pedestrians or other vehicles',
        '接近交叉路前的停车位置时，前方的信号变成了黄灯，此时只有在无法安全停车的情况下才可以不停车通过交叉路': 'When approaching the stopping position before an intersection, the signal ahead turns yellow. At this time, you can only pass through the intersection without stopping if you cannot safely stop',
        '在交叉路附近行驶时，因为紧急车辆接近，所以没有进入交叉路，而是靠道路的左侧暂时停了下来': 'When driving near an intersection, because an emergency vehicle was approaching, I did not enter the intersection but temporarily stopped on the left side of the road',
        '刹车时，刚一开始要尽量轻踩，然后慢慢地踩到需要的强度': 'When braking, start by pressing lightly, then gradually press to the required strength',
        '在交通量少的交叉路，在交叉路近前发出右转弯或左转弯的信号即可': 'At intersections with light traffic, you only need to signal a right or left turn near the intersection',
        '最大载重量为4,000kg的货车用普通驾驶执照即可驾驶': 'Trucks with a maximum load capacity of 4,000kg can be driven with an ordinary driver\'s license',
        '饮酒后不得驾驶，若是酒精度数低的啤酒，喝了以后驾驶也无妨': 'You must not drive after drinking alcohol, but if it is low-alcohol beer, you can drive after drinking',
        '该标志表示道路到前方已是尽头': 'This sign indicates that the road ends ahead',
        '轻型摩托车和小型特殊汽车可以在公共汽车专用通行带通行，但大型二轮摩托车等除了左转弯或不得已的情况以外不能通行': 'Light motorcycles and small special vehicles can travel in dedicated bus lanes, but large motorcycles cannot except when turning left or in unavoidable circumstances',
    }
    
    # 先匹配完整句子（按长度降序排列，优先匹配长句子）
    sorted_translations = sorted(full_sentence_translations.items(), key=lambda x: len(x[0]), reverse=True)
    for zh, en in sorted_translations:
        if zh in result:
            result = result.replace(zh, en)
            break  # 只替换第一个匹配的
    
    # 基础词汇翻译
    basic_translations = {
        '该标志': 'This sign',
        '表示': 'indicates',
        '禁止': 'prohibited',
        '注意': 'pay attention',
        '必须': 'must',
        '不得': 'must not',
        '可以': 'may',
        '应该': 'should',
        '需要': 'need to',
        '最好': 'it is best to',
        '驾驶': 'driving',
        '车辆': 'vehicle',
        '道路': 'road',
        '交叉路': 'intersection',
        '人行横道': 'pedestrian crossing',
        '信号灯': 'traffic light',
        '绿灯': 'green light',
        '红灯': 'red light',
        '黄灯': 'yellow light',
        '右转弯': 'right turn',
        '左转弯': 'left turn',
        '超车': 'overtaking',
        '停车': 'parking',
        '行驶': 'driving',
        '通行': 'passing',
        '行人': 'pedestrian',
        '自行车': 'bicycle',
        '摩托车': 'motorcycle',
        '汽车': 'car',
        '公共汽车': 'bus',
        '出租车': 'taxi',
        '刹车': 'brake',
        '加速': 'accelerate',
        '减速': 'slow down',
        '缓行': 'drive slowly',
        '速度': 'speed',
        '安全': 'safety',
        '危险': 'danger',
        '执照': 'license',
        '驾驶执照': 'driver\'s license',
        '标志': 'sign',
        '标示': 'marking',
        '警察': 'police',
        '前方': 'ahead',
        '后方': 'behind',
        '左侧': 'left side',
        '右侧': 'right side',
        '中心线': 'center line',
        '车道': 'lane',
        '路口': 'intersection',
        '铁路道': 'railroad crossing',
        '坡道': 'slope',
        '上坡': 'uphill',
        '下坡': 'downhill',
        '二轮车': 'motorcycle',
        '四轮车': 'four-wheeled vehicle',
        '大型车辆': 'large vehicle',
        '中型车辆': 'medium vehicle',
        '普通车辆': 'ordinary vehicle',
        '轻型车辆': 'light vehicle',
        '反方向': 'opposite direction',
        '直行': 'go straight',
        '变道': 'change lanes',
        '让路': 'yield',
        '让道': 'yield',
        '超车': 'overtake',
        '追车': 'chase',
        '掉头': 'U-turn',
        '横穿': 'cross',
        '横过': 'cross',
        '通过': 'pass through',
        '进入': 'enter',
        '驶入': 'enter',
        '驶出': 'exit',
        '驶来': 'approach',
        '驶去': 'go',
        '接近': 'approach',
        '距离': 'distance',
        '车距': 'distance between vehicles',
        '车间距离': 'distance between vehicles',
        '速度': 'speed',
        '减速': 'slow down',
        '加速': 'accelerate',
        '保持': 'maintain',
        '保持速度': 'maintain speed',
        '放慢速度': 'slow down',
        '加快速度': 'speed up',
        '提高速度': 'increase speed',
        '缩短': 'shorten',
        '延长': 'extend',
        '确认': 'confirm',
        '注意': 'pay attention',
        '观察': 'observe',
        '看到': 'see',
        '看到': 'see',
        '觉察': 'notice',
        '发现': 'discover',
        '预测': 'predict',
        '估计': 'estimate',
        '判断': 'judge',
        '决定': 'decide',
        '选择': 'choose',
        '采取': 'take',
        '执行': 'execute',
        '操作': 'operate',
        '控制': 'control',
        '管理': 'manage',
        '处理': 'handle',
        '应对': 'respond',
        '避免': 'avoid',
        '防止': 'prevent',
        '阻止': 'prevent',
        '制止': 'stop',
        '停止': 'stop',
        '停车': 'park',
        '驻车': 'park',
        '暂时停车': 'temporary stop',
        '紧急停车': 'emergency stop',
        '急刹车': 'emergency brake',
        '紧急刹车': 'emergency brake',
        '刹车': 'brake',
        '制动': 'brake',
        '制动器': 'brake',
        '手制动器': 'hand brake',
        '发动机制动器': 'engine brake',
        '发动机制动': 'engine brake',
        '前照灯': 'headlight',
        '前灯': 'headlight',
        '车头灯': 'headlight',
        '方向指示灯': 'turn signal',
        '转向灯': 'turn signal',
        '信号': 'signal',
        '手势信号': 'hand signal',
        '手信号': 'hand signal',
        '闪烁': 'flash',
        '闪烁前照灯': 'flash headlights',
        '鸣笛': 'sound the horn',
        '警音器': 'horn',
        '喇叭': 'horn',
        '变速杆': 'gear lever',
        '变速档': 'gear',
        '档位': 'gear',
        'P档': 'P gear',
        'N档': 'N gear',
        'R档': 'R gear',
        'D档': 'D gear',
        '2档': '2nd gear',
        'L档': 'L gear',
        '1档': '1st gear',
        '空档': 'neutral',
        '离合器': 'clutch',
        '脱开离合器': 'disengage clutch',
        '加速踏板': 'accelerator pedal',
        '油门': 'throttle',
        '制动踏板': 'brake pedal',
        '刹车踏板': 'brake pedal',
        '方向盘': 'steering wheel',
        '打方向盘': 'turn steering wheel',
        '转动方向盘': 'turn steering wheel',
        '急打方向盘': 'sudden steering',
        '急转方向盘': 'sudden steering',
        '安全带': 'seat belt',
        '腰部安全带': 'lap belt',
        '肩部安全带': 'shoulder belt',
        '系': 'fasten',
        '系上': 'fasten',
        '松开': 'release',
        '松开制动踏板': 'release brake pedal',
        '目视检查': 'visual inspection',
        '检查': 'check',
        '确认': 'confirm',
        '验证': 'verify',
        '测试': 'test',
        '试验': 'test',
        '启动': 'start',
        '启动发动机': 'start engine',
        '关闭': 'close',
        '关闭发动机': 'turn off engine',
        '熄火': 'stall',
        '发动机熄火': 'engine stall',
        '故障': 'breakdown',
        '故障车': 'broken-down vehicle',
        '故障车辆': 'broken-down vehicle',
        '停滞不动': 'stall',
        '停止行驶': 'stop',
        '停止': 'stop',
        '停车': 'park',
        '驻车': 'park',
        '暂时停车': 'temporary stop',
        '紧急停车': 'emergency stop',
        '急刹车': 'emergency brake',
        '紧急刹车': 'emergency brake',
        '分数次踩踏刹车': 'tap brakes several times',
        '分数次踩了刹车': 'tapped brakes several times',
        '踩踏': 'step on',
        '踩下': 'press down',
        '用力踩下': 'press firmly',
        '一下子用力踩下': 'press firmly at once',
        '保持': 'maintain',
        '保持踏板压力': 'maintain pedal pressure',
        '保持速度': 'maintain speed',
        '保持原有速度': 'maintain original speed',
        '保持原来速度': 'maintain original speed',
        '保持原速': 'maintain original speed',
        '保持高速': 'maintain high speed',
        '保持这种状态': 'maintain this state',
        '保持一定距离': 'maintain a certain distance',
        '保持安全距离': 'maintain safe distance',
        '保持一定距离行驶': 'drive at a certain distance',
        '保持车距': 'maintain distance between vehicles',
        '保持车间距离': 'maintain distance between vehicles',
        '缩短车距': 'shorten distance between vehicles',
        '缩短与前面车辆的距离': 'shorten distance to vehicle ahead',
        '缩短与前车辆的车距': 'shorten distance to vehicle ahead',
        '取足车距': 'ensure sufficient distance',
        '充分取足车距': 'ensure sufficient distance',
        '车距得不到保证': 'distance cannot be guaranteed',
        '车间距离得不到保证': 'distance between vehicles cannot be guaranteed',
        '距离': 'distance',
        '车距': 'distance between vehicles',
        '车间距离': 'distance between vehicles',
        '安全距离': 'safe distance',
        '一定距离': 'certain distance',
        '充分距离': 'sufficient distance',
        '足够距离': 'sufficient distance',
        '不足距离': 'insufficient distance',
        '缩短距离': 'shorten distance',
        '延长距离': 'extend distance',
        '保持距离': 'maintain distance',
        '确保距离': 'ensure distance',
        '保证距离': 'guarantee distance',
        '距离': 'distance',
        '接近': 'approach',
        '驶近': 'approach',
        '接近': 'approach',
        '逐渐接近': 'gradually approach',
        '快速接近': 'quickly approach',
        '缓慢接近': 'slowly approach',
        '紧急接近': 'urgently approach',
        '接近碰撞边缘': 'approach collision point',
        '接近': 'approach',
        '靠近': 'approach',
        '贴近': 'get close to',
        '逼近': 'approach',
        '借道': 'borrow lane',
        '插入': 'cut in',
        '加塞': 'cut in',
        '强行加塞': 'forcibly cut in',
        '插入前方': 'cut in front',
        '插入': 'cut in',
        '让插入': 'allow to cut in',
        '不让插入': 'do not allow to cut in',
        '为不让其插入': 'to prevent it from cutting in',
        '为不让其插入在前': 'to prevent it from cutting in front',
        '缩短车距为不让其插入': 'shorten distance to prevent cutting in',
        '变道': 'change lanes',
        '改变车道': 'change lanes',
        '变更车道': 'change lanes',
        '改变行进路线': 'change route',
        '变更行进路线': 'change route',
        '变到左侧的车道': 'change to left lane',
        '变到右侧的车道': 'change to right lane',
        '变到中央线附近': 'change to near center line',
        '变道': 'change lanes',
        '要变道': 'want to change lanes',
        '准备变道': 'prepare to change lanes',
        '让其容易地驶入': 'make it easy to enter',
        '让其容易地驶入我车的前方': 'make it easy to enter in front of my vehicle',
        '为了让其容易地驶入我车的前方': 'to make it easy to enter in front of my vehicle',
        '不让其变道': 'do not allow lane change',
        '所以不让其变道': 'so do not allow lane change',
        '加速车道': 'acceleration lane',
        '加速车道上的车辆': 'vehicle on acceleration lane',
        '加速车道上的车辆就可以容易地驶入主干道': 'vehicles on acceleration lane can easily enter main road',
        '加速车道上的车辆': 'vehicles on acceleration lane',
        '为超越加速车道上的车辆': 'to overtake vehicles on acceleration lane',
        '于是保持原有速度行进': 'so maintain original speed',
        '于是保持原有速度行进以超越加速车道上的车辆': 'so maintain original speed to overtake vehicles on acceleration lane',
        '保持原有速度行进以超越加速车道上的车辆': 'maintain original speed to overtake vehicles on acceleration lane',
        '超车': 'overtake',
        '超车': 'overtaking',
        '准备超车': 'prepare to overtake',
        '要超车': 'want to overtake',
        '会超车': 'will overtake',
        '可能超车': 'may overtake',
        '可以超车': 'can overtake',
        '不能超车': 'cannot overtake',
        '禁止超车': 'overtaking prohibited',
        '不得超车': 'must not overtake',
        '不可超车': 'cannot overtake',
        '停止超车': 'stop overtaking',
        '终止超车': 'stop overtaking',
        '会终止超车': 'will stop overtaking',
        '会觉察到有车辆接近于它并会终止超车': 'will notice vehicle approaching and stop overtaking',
        '对方的轿车会觉察到有车辆接近于它并会终止超车': 'opposing car will notice vehicle approaching and stop overtaking',
        '于是保持原来的速度行驶过去': 'so maintain original speed and pass',
        '对方的轿车要超车是危险的': 'opposing car wanting to overtake is dangerous',
        '为让其停止超车': 'to make it stop overtaking',
        '鸣笛制止并保持原来的车速行进': 'sound horn to stop and maintain original speed',
        '鸣笛制止': 'sound horn to stop',
        '追车': 'chase',
        '禁止追车': 'chasing prohibited',
        '掉头': 'U-turn',
        '禁止掉头': 'U-turn prohibited',
        '禁止掉头路段': 'no U-turn section',
        '禁止掉头路段"结束"': 'end of no U-turn section',
        '横穿': 'cross',
        '横过': 'cross',
        '横穿道路': 'cross road',
        '横过道路': 'cross road',
        '横穿': 'cross',
        '横过': 'cross',
        '不能横穿': 'cannot cross',
        '不得横穿': 'must not cross',
        '不可横穿': 'cannot cross',
        '禁止横穿': 'crossing prohibited',
        '横穿人行道': 'cross sidewalk',
        '横穿路侧带': 'cross roadside strip',
        '即使车辆是为了进出面向道路的场所，也不能横穿人行道和路侧带': 'even if vehicle is for entering/exiting road-facing place, cannot cross sidewalk and roadside strip',
        '通过': 'pass through',
        '通过交叉路口': 'pass through intersection',
        '通过铁路道': 'pass through railroad crossing',
        '通过铁路道内': 'pass through railroad crossing',
        '通过轨道岔口': 'pass through railroad crossing',
        '通过轨道岔口时': 'when passing through railroad crossing',
        '通过深水积存地': 'pass through deep water accumulation',
        '通过': 'pass through',
        '径直通过': 'pass straight through',
        '直线通过': 'pass straight through',
        '径直驶来': 'come straight',
        '直行过来': 'come straight',
        '直行驶来': 'come straight',
        '直行': 'go straight',
        '直行通过': 'pass straight through',
        '径直通过': 'pass straight through',
        '直线通过': 'pass straight through',
        '径直驶来': 'come straight',
        '直行过来': 'come straight',
        '直行驶来': 'come straight',
        '直行车辆': 'straight-going vehicle',
        '直行车': 'straight-going vehicle',
        '直行车的通行': 'passage of straight-going vehicle',
        '不可妨碍直行车的通行': 'cannot obstruct passage of straight-going vehicle',
        '也不可妨碍直行车的通行': 'also cannot obstruct passage of straight-going vehicle',
        '即使自己的车已先进入交叉路，也不可妨碍直行车的通行': 'even if own vehicle entered intersection first, cannot obstruct passage of straight-going vehicle',
        '进入': 'enter',
        '驶入': 'enter',
        '进入交叉路口': 'enter intersection',
        '进入交叉路': 'enter intersection',
        '进入隧道': 'enter tunnel',
        '进入': 'enter',
        '先前进入': 'entered first',
        '先前进入交叉路口': 'entered intersection first',
        '先前进入交叉路': 'entered intersection first',
        '已先进入交叉路': 'entered intersection first',
        '即使自己的车已先进入交叉路': 'even if own vehicle entered intersection first',
        '进入交叉路口以前': 'before entering intersection',
        '在进人交叉路口以前': 'before entering intersection',
        '驶出': 'exit',
        '驶出该通行带': 'exit the lane',
        '必须立即驶出该通行带': 'must immediately exit the lane',
        '其它汽车必须立即驶出该通行带': 'other vehicles must immediately exit the lane',
        '当公共汽车接近时，其它汽车必须立即驶出该通行带': 'when bus approaches, other vehicles must immediately exit the lane',
        '驶来': 'approach',
        '驶去': 'go',
        '驶近': 'approach',
        '驶来': 'approach',
        '反方向驶来': 'approach from opposite direction',
        '从反方向驶来': 'approach from opposite direction',
        '反方向上的车辆驶来': 'vehicle approaches from opposite direction',
        '反方向上的二轮车驶来': 'motorcycle approaches from opposite direction',
        '反方向上的二轮车或小路上驶来的二轮车': 'motorcycle from opposite direction or from small road',
        '反方向上的二轮车或小路上驶来的二轮车,已经注意到了我方车辆的行驶': 'motorcycle from opposite direction or from small road has noticed our vehicle\'s movement',
        '因而就不会出现在行进的道路上': 'therefore will not appear on the road ahead',
        '所以还是保持原来的速度行进': 'so maintain original speed',
        '反方向上的二轮车在靠中央线行驶': 'motorcycle from opposite direction is driving near center line',
        '它有可能右转弯驶入左侧的小路里': 'it may turn right into left side small road',
        '所以注意其动向并减速': 'so pay attention to its movement and slow down',
        '反方向上的二轮车或小路上驶来的二轮车': 'motorcycle from opposite direction or from small road',
        '已经注意到了我方车辆的行驶': 'has noticed our vehicle\'s movement',
        '因而就不会出现在行进的道路上': 'therefore will not appear on the road ahead',
        '所以还是保持原来的速度行进': 'so maintain original speed',
        '反方向上的二轮车在靠中央线行驶': 'motorcycle from opposite direction is driving near center line',
        '它有可能右转弯驶入左侧的小路里': 'it may turn right into left side small road',
        '所以注意其动向并减速': 'so pay attention to its movement and slow down',
        '反方向上的二轮车或小路上驶来的二轮车': 'motorcycle from opposite direction or from small road',
        '已经注意到了我方车辆的行驶': 'has noticed our vehicle\'s movement',
        '因而就不会出现在行进的道路上': 'therefore will not appear on the road ahead',
        '所以还是保持原来的速度行进': 'so maintain original speed',
        '反方向上的二轮车在靠中央线行驶': 'motorcycle from opposite direction is driving near center line',
        '它有可能右转弯驶入左侧的小路里': 'it may turn right into left side small road',
        '所以注意其动向并减速': 'so pay attention to its movement and slow down',
    }
    
    # 按长度降序排列，先替换长的短语
    sorted_translations = sorted(basic_translations.items(), key=lambda x: len(x[0]), reverse=True)
    
    for zh, en in sorted_translations:
        result = result.replace(zh, en)
    
    # 清理格式
    result = re.sub(r'\s+', ' ', result).strip()
    result = result.replace('，', ', ')
    result = result.replace('。', '.')
    result = result.replace('、', ', ')
    result = result.replace('：', ': ')
    result = result.replace('；', '; ')
    result = result.replace('？', '?')
    result = result.replace('！', '!')
    result = result.replace('"', '"')
    result = result.replace('"', '"')
    result = result.replace(''', "'")
    result = result.replace(''', "'")
    
    return prefix + result

def translate_zh_to_ja(text):
    """中文到日文翻译 - 使用我的翻译能力"""
    if not text or not text.strip():
        return ""
    
    # 保存题号
    text = text.strip()
    number_match = re.match(r'^(\d+)\.\s*', text)
    prefix = number_match.group(0) if number_match else ''
    content = re.sub(r'^\d+\.\s*', '', text)
    
    # 处理explanation标准开头
    if content.startswith('根据题目描述，该说法是正确的'):
        rest = re.sub(r'^根据题目描述，该说法是正确的。\s*', '', content)
        return prefix + '問題文の通り、この記述は正しいです。' + translate_zh_to_ja(rest)
    elif content.startswith('根据题目描述，该说法是错误的') or content.startswith('根据题目描述，该说法是误的'):
        rest = re.sub(r'^根据题目描述，该说法是(错误的|误的)。\s*', '', content)
        return prefix + '問題文の通り、この記述は誤りです。' + translate_zh_to_ja(rest)
    
    if content in ['如题所述', '如题目所述']:
        return prefix + '問題文の通り'
    
    # 使用规则进行翻译
    result = content
    
    # 扩展的完整句子翻译（日文，优先匹配长句子）
    full_sentence_translations_ja = {
        '从后面看，图中的手势信号是右转弯、掉头或在同一方向行驶中向右改变车道的信号': '後ろから見ると、図中の手信号は右折、転回、または同一方向走行中に右に車線変更する信号です',
        '在坊碍交通的时候，即使在未禁止的地方，也不能横穿道路或掉头': '交通を妨げる場合、禁止されていない場所でも道路を横断したり転回したりしてはいけません',
        '在前方道路有障碍物的时候，应当提前减速或停车，给对面来车让道': '前方の道路に障害物がある場合、事前に減速または停車し、対向車に道を譲るべきです',
        '在交叉路附近以外的道路行驶的车辆，在有紧急车辆驶近时，如果靠左侧让行，一定要暂时停车': '交差点付近以外の道路を走行する車両は、緊急車両が接近した場合、左側に寄せて譲る場合は必ず一時停止しなければなりません',
        '右转弯时，如果反方向有直行车辆驶来，即使自己的车已先进入交叉路，也不可妨碍直行车的通行': '右折時、対向から直進車両が来た場合、自分の車が先に交差点に入っても、直進車の通行を妨げてはいけません',
        '内轮差是指，汽车在右转弯时，后轮比前轮更靠外侧': '内輪差とは、自動車が右折する際、後輪が前輪より外側に寄ることを指します',
        '在普通道路的法定最高速度，所有的机动车都是每小时60公里': '普通道路の法定最高速度では、すべての自動車は時速60キロメートルです',
        '申考大型驾驶证的原则需具备以下条件：年龄在21岁及以上，且取得普通驾驶证期间合计3年及以上。不过，若是修完政令指定教程的人员，19岁及以上且取得普通驾驶证期间合法1年及以上即可申考': '大型免許の申請原則は以下の条件が必要です：年齢21歳以上、かつ普通免許取得期間合計3年以上。ただし、政令指定教程を修了した者は、19歳以上で普通免許取得期間1年以上で申請可能です',
        '为进出临近道路的场所内横穿人行道和路侧带时，如果没有行人通行，不必在人行道和路侧带前暂时停车': '道路に面した場所への出入りのために横断歩道や路側帯を横断する際、歩行者がいない場合は、横断歩道や路側帯の前で一時停止する必要はありません',
        '有图中标志的道路，原则禁止车辆通行，但在路旁有车库的车辆等，取得警察署的许可后，车辆可缓行通过': '図中の標識がある道路は原則として車両通行禁止ですが、路傍に車庫がある車両などは、警察署の許可を得た後、車両は徐行して通過できます',
        '在这个标志的场所,不能停泊车或临时停车': 'この標識のある場所では、駐車または一時駐車はできません',
        '落石危险': '落石危険',
        '在视线较差的左弯道上,靠中央线行驶能够迅速确认弯道前方,因此很安全': '見通しの悪い左カーブでは、中央線に寄って走行するとカーブ前方を迅速に確認できるため、安全です',
        '下雨的时候,空走距离变长,但是制动距离不变': '雨の日は空走距離が長くなりますが、制動距離は変わりません',
        '以每小时 60 公里的速度猛烈撞击钢筋混凝土墙壁时,会受到和从 5 层程度建筑物落下(大约 14 米)时相同程度的冲击': '時速60キロメートルで鉄筋コンクリートの壁に激突すると、5階建ての建物から落下（約14メートル）した時と同じ程度の衝撃を受けます',
        '中央线不一定设置在道路中央': '中央線は必ずしも道路の中央に設置されているとは限りません',
        '在有信号灯的交叉路想往右转弯的时候,因对面是绿灯进入了交叉路，但右转弯方向的信号是红灯的，此时在交叉路中停下来了': '信号機のある交差点で右折しようとしたとき、対向が青信号で交差点に入ったが、右折方向の信号が赤信号だったため、交差点内で停車した',
        '右转弯时 要在交叉路跟前靠道路中央行驶': '右折時は交差点の手前で道路中央に寄って走行する',
        '由于车辆的重心会升高或失去平衡，容易侧翻,因此货物应当尽量装在低处，并保持左右平衡': '車両の重心が上がったりバランスを失ったりすると横転しやすいため、荷物はできるだけ低い位置に積み、左右のバランスを保つべきです',
        '任何情况都不能在高速上停车': 'いかなる場合でも高速道路で駐車してはいけません',
        '驾驶员应尊重行人与其他驾驶员的立场,本着相互礼让的原则通行': '運転者は歩行者や他の運転者の立場を尊重し、相互に譲り合う原則に基づいて通行すべきです',
        '绿灯因为不是前进的命令,所以在交叉路，人行横道，铁路道等地方,就出不来的交通状态的时候，即使是绿灯也不能进入': '青信号は前進の命令ではないため、交差点、横断歩道、踏切などで出られない交通状態のときは、青信号でも進入できません',
        '即使以同样的速度行走，也会感到夜间比白天慢': '同じ速度で走行しても、夜間は昼間より遅く感じます',
        '在交叉路左转弯时,左后方有自行车快速接近,因为有可能刮到,所按喇叭抢先左转': '交差点で左折する際、左後方から自転車が急速に接近してきたため、接触の可能性があるので、クラクションを鳴らして先に左折した',
        '在禁止停泊车的道路上停车并在车中等待友人 5 分钟的行为是非法停车': '駐車禁止の道路に駐車して車内で友人を5分待つ行為は違法駐車です',
        '在转弯时,与速度无关,一定会产生内轮差': 'カーブ時は速度に関係なく、必ず内輪差が発生します',
        '在交叉路附近通行时，因为紧急车辆接近，所以靠左侧放慢了速度': '交差点付近を通行する際、緊急車両が接近したため、左側に寄せて速度を落とした',
        '驾驶执照的条款栏上所记载的「眼镜等」含使用隐形眼镜': '運転免許の条件欄に記載されている「眼鏡等」にはコンタクトレンズの使用も含まれます',
        '因为前方车辆发出了右转弯信号准备向右侧改变车道，所以鸣笛提醒其注意后，从右侧超了过去': '前方の車両が右折信号を出して右側に車線変更しようとしたため、クラクションで注意を促した後、右側から追い越した',
        '由于气温下降，如果在家前面的道路上泼水的话有可能使道路结冰，但为了防止起灰泼了水': '気温が下がったため、家の前の道路に水をまくと道路が凍結する可能性があるが、ほこりを防ぐために水をまいた',
        '在单行路上给紧急车辆让路时，有时要靠向道路的右侧': '一方通行路で緊急車両に道を譲る際、道路の右側に寄る場合があります',
        '过度地鸣笛不仅产生噪音还刺激对方的情绪，是引起麻烦的原因': '過度にクラクションを鳴らすことは騒音を発生させるだけでなく、相手の感情を刺激し、トラブルの原因となります',
        '面对该信号的车辆及有轨电车，不能越过停车位置前行': 'この信号に面する車両及び路面電車は、停止位置を越えて進行してはいけません',
        '通过自行车的侧面在交叉路左转弯时，因为有将自行车卷入的危险，所以鸣笛提醒自行车注意后先向左转弯了': '自転車の横を通過して交差点で左折する際、自転車を巻き込む危険があるため、クラクションで自転車に注意を促した後、先に左折した',
        '在同一方向有三条车辆通行带的道路上，驾驶普通汽车一直在左数第三条通行带上行驶了': '同一方向に3車線の車両通行帯がある道路で、普通自動車を左から3番目の通行帯で走行し続けた',
        '普通汽车在没有用标志或标示指定的普通公路上的最高限速是时速60公里': '標識や標示で指定されていない普通道路での普通自動車の最高速度は時速60キロメートルです',
        '驾驶座席靠背的位置应调整到双手握方向盘时，肘部微曲的状态相一致': '運転席の背もたれの位置は、両手でハンドルを握ったとき、肘が軽く曲がった状態に合わせて調整すべきです',
        '要改变车道时，因后方有车辆已接近，所以没有改变车道让了路': '車線変更しようとしたとき、後方から車両が接近していたため、車線変更せずに道を譲った',
        '因贴有初学者标记的汽车以最高限速以下的速度行驶，所以鸣笛让对方避到道路左侧后驶了过去': '初心者マークを貼った車が最高速度以下の速度で走行していたため、クラクションで相手を道路左側に避けさせた後、通過した',
        '让儿童坐在前面的座席不仅对儿童非常危险，也影响驾驶操作': '子供を前席に座らせることは子供にとって非常に危険であるだけでなく、運転操作にも影響します',
        '因为在没有人行横道的交叉路有行人横过，为不妨碍其通行，暂时停了下来等待行人横过结束': '横断歩道のない交差点で歩行者が横断していたため、その通行を妨げないよう、一時停止して歩行者の横断が終わるのを待った',
        '路面被雨水淋湿、轮胎磨损严重时，与干燥路面轮胎状况良好时相比，停车距离基本没有差别': '路面が雨で濡れ、タイヤが激しく摩耗している場合、乾燥した路面でタイヤの状態が良好な場合と比較して、停止距離は基本的に差がありません',
        '不能进入有该标示的路侧带内驻车或停车': 'この標示のある路側帯内に進入して駐車または停車することはできません',
        '禁止在上坡的坡顶附近及陡下坡超越汽车及轻型摩托车': '上り坂の頂上付近および急な下り坂での自動車および原動機付自転車の追い越しは禁止されています',
        '红灯闪烁时，面对该信号的车辆及有轨电车，要在停车位置暂时停车，确认安全后可以前行': '赤信号が点滅しているとき、この信号に面する車両及び路面電車は、停止位置で一時停止し、安全を確認した後、進行できます',
        '无论道路状况或其它交通状况如何，都禁止越入道路中心以右的部分通行': '道路状況やその他の交通状況に関わらず、道路の中心から右側の部分に入ることは禁止されています',
        '根据标志要暂时停车的交叉路是容易发生交通事故的危险场所，因此必须暂时停车确认安全后再通行': '標識により一時停止が必要な交差点は交通事故が発生しやすい危険な場所であるため、必ず一時停止して安全を確認した後、通行しなければなりません',
        '在停止着的幼儿园、学校班车旁边通过时，必须暂时停车确认安全': '停車している幼稚園・学校の送迎バスの横を通過する際は、必ず一時停止して安全を確認しなければなりません',
        '所谓超车，是指改变车道驶到前面正在行驶的车辆的前方，因为驾驶操作复杂，所以尽量不要超车，以安全的速度行驶': '追い越しとは、車線を変更して前方を走行している車両の前に出ることです。運転操作が複雑なため、できるだけ追い越しを避け、安全な速度で走行してください',
        '儿童安全椅在生病等不得已的情况下可以不使用': 'チャイルドシートは病気などのやむを得ない場合、使用しなくてもよい',
        # 第二批翻译规则（日文）
        '该标志表示是道路的中心或中心线': 'この標識は道路の中心または中心線を示しています',
        '在交叉路内，发现从后方有紧急车辆接近时，必须立即原地停车': '交差点内で後方から緊急車両が接近していることを発見した場合、直ちにその場で停車しなければなりません',
        '因为前方的信号从黄色变成了红色，所以为提醒后面驶来的车辆停车分数次踩了刹车': '前方の信号が黄色から赤に変わったため、後続車に停車を知らせるために数回ブレーキを踏みました',
        '左右转弯等行为结束时，收回所发出信号的时间是其行为结束的约3秒钟之后': '左右折などの行為が終了したとき、発した信号を取り消す時間は、その行為が終了してから約3秒後です',
        '取得普通临时驾驶执照的人，如果是为了练习，可以驾驶轻型摩托车': '普通仮免許を取得した者は、練習のためであれば、原動機付自転車を運転できます',
        '腰部安全带松弛地系在腹部即可': '腰のシートベルトは腹部にゆるく締めるだけでよい',
        '该标志是表示注意危险的警告标志': 'この標識は危険に注意を促す警告標識です',
        '在设有公共汽车等优先通行带的道路上，为了向左转弯通过了该车辆通行带': 'バスなどの優先通行帯が設置されている道路で、左折するためにその車両通行帯を通過しました',
        '汽车驾驶员在有行人的安全地带旁边通过时必须缓行': '自動車の運転者は、歩行者の安全地帯の横を通過する際は徐行しなければなりません',
        '驾驶汽车时不得随意改变车道，但在不得已的情况下改变车道时，需要利用后视镜或通过目视来确认安全': '自動車を運転する際は、随意に車線変更してはいけませんが、やむを得ない場合に車線変更する際は、バックミラーを利用するか、目視で安全を確認する必要があります',
        '因为自动变速车的基本要领是操作加速踏板和刹车踏板，所以不必特别注意变速杆的操作': 'オートマチック車の基本は、アクセルペダルとブレーキペダルの操作なので、変速レバーの操作に特に注意する必要はありません',
        '该标志指禁止车辆进入，不能从有标志的方向进入': 'この標識は車両進入禁止を示しており、標識のある方向から進入することはできません',
        '在没有车辆通行带的道路上，除了超车等不得已的情况以外，要靠道路的左侧通行': '車両通行帯のない道路では、追い越しなどのやむを得ない場合を除き、道路の左側を通行しなければなりません',
        '通过铁路道内时，为了防止发动机熄火，最好尽早变速一气通过': '踏切内を通過する際は、エンジンが停止するのを防ぐため、早めにギアチェンジして一気に通過するのがよいでしょう',
        '汽车驾驶员不得做产生较大噪音等明显给他人带来麻烦的急起动、急加速及空转': '自動車の運転者は、大きな騒音を発生させるなど、明らかに他人に迷惑をかける急発進、急加速、アイドリングをしてはいけません',
        '超车时，首先要边向右侧靠近边打开右侧方向指示灯，其次最好用眼睛确认后方的安全': '追い越しの際は、まず右側に寄りながら右ウインカーを出し、次に目で後方の安全を確認するのが最善です',
        '不得向即将驾驶的人敬酒或劝酒': '運転しようとしている人に酒を勧めたり、飲酒を促したりしてはいけません',
        '该标志表示路基容易塌落，需要注意': 'この標識は路肩が崩れやすいことを示しており、注意が必要です',
        '因为停在车站的公共汽车通过方向指示灯等发出了起动信号，所以缓行让公共汽车先起动了': '停留所に停車していたバスがウインカーなどで発進の合図を出したので、徐行してバスを先に発進させました',
        '在上坡的坡顶附近及陡下坡处必须缓行': '上り坂の頂上付近および急な下り坂では、必ず徐行しなければなりません',
        '超越前面的车辆时，必须鸣笛引起对方注意后超车': '前方の車両を追い越す際は、クラクションで相手に注意を促した後、追い越さなければなりません',
        '装有防锁死刹车系统的车辆急刹车时，如果不一气用力踩下刹车并一直踩住的话，系统就不动作': 'アンチロックブレーキシステムを搭載した車両で急ブレーキをかける場合、一気に強く踏み込んで踏み続けないとシステムが作動しません',
        '该标志为禁止右转弯的标志': 'この標識は右折禁止の標識です',
        '汽车和轻型摩托车除了为进出面向道路的场所而横过以外，不得在人行道、路侧带及自行车道等处通行': '自動車および原動機付自転車は、道路に面した場所への出入りのために横断する場合を除き、歩道、路側帯、自転車道などを通行してはいけません',
        '驾驶汽车时，不得超过标志或标示所示的最高限速行驶': '自動車を運転する際は、標識や標示で示された最高速度を超えて走行してはいけません',
        '在上车之前，如果确认了车前后是否有人，就没有必要连汽车的下面也确认': '乗車前に車の前後に人がいるかどうかを確認すれば、車の下まで確認する必要はありません',
        '被其它车辆超车时，如果没有充分的余地超越对方，必须尽量靠向左侧让路': '他の車両に追い越される際、相手を追い越す十分な余地がない場合は、できるだけ左側に寄せて道を譲らなければなりません',
        '驾驶员必须锁上汽车的安全栓，以免同乘者无意中打开车门': '運転者は、同乗者が誤ってドアを開けないように、車の安全ロックをかけなければなりません',
        '在有该标志的地方，总排气量在125cc以下的普通二轮摩托车不能通行': 'この標識がある場所では、総排気量125cc以下の普通自動二輪車は通行できません',
        '即使警察署和消防署等前面标有禁止停车部分的标示，因为是紧急情况时的标示，所以，除了紧急情况以外，可以进入标示部分停车': '警察署や消防署などの前に駐車禁止部分の標示があっても、緊急時の標示であるため、緊急時以外は標示部分に進入して駐車できます',
        '在雪地驾驶时，由于停车距离比在干燥的柏油路要长，所以必须时常控制速度小心驾驶': '雪道を運転する際は、停止距離が乾燥したアスファルト道路より長いため、常に速度をコントロールして慎重に運転しなければなりません',
        '右转弯或左转弯发出信号的时间是其行为开始大约3秒之前': '右折または左折の信号を出す時間は、その行為が始まる約3秒前です',
        '用大型特殊驾驶执照可以驾驶大型特殊汽车、小型特殊汽车及轻型摩托车': '大型特殊免許で大型特殊自動車、小型特殊自動車、原動機付自転車を運転できます',
        '在驾驶途中因有急事打车载电话或手机时，最好将车停靠在道路的左端后再打': '運転中に急用で車載電話や携帯電話をかける際は、道路の左端に停車してからかけるのが最善です',
        '该标示表示是自行车横道': 'この標示は自転車横断帯を示しています',
        '在交叉路近前用黄线划有车辆通行带的地方，不能向指定以外的方向改变车道': '交差点の手前で黄線で車両通行帯が引かれている場所では、指定以外の方向に車線変更することはできません',
        '即使标志等指定的最高限速为时速20公里，在交通量少的时候，也可以超过该速度驾驶': '標識などで指定された最高速度が時速20キロメートルであっても、交通量が少ないときは、その速度を超えて運転してもよい',
        '接近人行横道时，除了明显没有行人及自行车横过的情况以外，必须以能够在其近前停车的速度行驶': '横断歩道に接近する際は、明らかに歩行者や自転車が横断していない場合を除き、その手前で停止できる速度で走行しなければなりません',
        '即使是在用黄线划分的车辆通行带，只要后面没有车辆，就可以越过黄线改变车道': '黄線で区画された車両通行帯であっても、後方に車両がなければ、黄線を越えて車線変更できます',
        '自动变速车的变速杆在P档或N档的位置时，由于溜车现象，有可能使车辆滑动': 'オートマチック車の変速レバーがPまたはNの位置にあるとき、転がり現象により、車両が滑る可能性があります',
        '不得突然加塞到其它车辆的前面及贴挤并行车辆': '他の車両の前に突然割り込んだり、並走する車両に貼り付いたりしてはいけません',
        '驾驶自动变速车时，如果停止时间可能较长，最好将变速杆切入N档，并使用手刹': 'オートマチック車を運転する際、停止時間が長くなる可能性がある場合は、変速レバーをNに入れ、ハンドブレーキを使用するのが最善です',
        '即使车辆是为了进出面向道路的场所，也不能横穿人行道和路侧带': '車両が道路に面した場所への出入りのためであっても、歩道や路側帯を横断することはできません',
        '驾驶员坐在驾驶座席上看车外时，视线被车身等妨碍，有看不到的部分，将看不到的部分称为死角': '運転者が運転席に座って車外を見るとき、視線が車体などに妨げられ、見えない部分があり、その見えない部分を死角と呼びます',
        '其它车辆准备超车时，在对方没有充分的余地超车的情况下，不需要特意让路': '他の車両が追い越しを準備しているとき、相手に追い越す十分な余地がない場合、特に道を譲る必要はありません',
        '不得醉酒后在道路上蹒跚行走或站着聊天等妨碍交通': '酒に酔った後、道路上でよろめいて歩いたり、立ち話をしたりして交通を妨げてはいけません',
        '该标志表示两条道路合流，道路变宽': 'この標識は2つの道路が合流し、道路が広くなることを示しています',
        '有紧急车辆接近，但因不在交叉路附近，所以靠道路的左侧让了路': '緊急車両が接近したが、交差点付近ではなかったため、道路の左側に寄せて道を譲った',
        '高明的刹车方法是不过度地使用制动器，尽量操作加速器慢慢地减速后停车': '上手なブレーキ方法は、ブレーキを過度に使用せず、できるだけアクセルを操作してゆっくり減速してから停車することです',
        '发出错误或不必要的信号，会使其它交通困惑，危险增加': '誤った信号や不要な信号を出すと、他の交通を混乱させ、危険が増加します',
        '该标志表示是专为行人通行而设的道路': 'この標識は歩行者専用の道路を示しています',
        '在交叉路和人行横道之前所表示的停车线只是车辆大概的停车位置，因此不用太在意停车线': '交差点や横断歩道の前に示された停止線は、車両の大まかな停止位置に過ぎないため、停止線をあまり気にする必要はありません',
        '由于河川涨水处于危险状态，警察禁止在桥上通行，但因为不是标志所示的禁止通行，所以无视警察的指示从桥上驶了过去': '河川の増水により危険な状態になったため、警察が橋上での通行を禁止したが、標識による通行禁止ではなかったため、警察の指示を無視して橋上を走行した',
        '卷入事故是指驾驶车辆左转弯时，将行人或自行车等卷入车辆的左后部轮胎或保险杠内的事故': '巻き込み事故とは、車両を左折する際、歩行者や自転車などを車両の左後部タイヤやバンパーに巻き込む事故を指します',
        '在一个人行走的儿童旁边通过时，必须暂时停车，让其安全通行': '一人で歩いている子供の横を通過する際は、必ず一時停止して、安全に通行させなければなりません',
        '临时驾驶执照是指要取得第一种驾驶执照或第二种驾驶执照的人为了练习等而驾驶大型汽车、中型汽车或普通汽车时的驾驶执照': '仮免許とは、第一種免許または第二種免許を取得しようとする者が練習などのために大型自動車、中型自動車、普通自動車を運転する際の免許です',
        '该标志表示禁止大型二轮摩托车、普通二轮摩托车及轻型摩托车通行': 'この標識は大型自動二輪車、普通自動二輪車、原動機付自転車の通行を禁止しています',
        '以比其它车辆慢的速度行驶时，应尽量靠道路的左侧行驶，以免影响交通畅通': '他の車両より遅い速度で走行する際は、交通の流れを妨げないよう、できるだけ道路の左側を走行すべきです',
        '通过铁路道时，为避免车轮陷入路边的铁轨里，应稍稍靠近道路中心通行': '踏切を通過する際は、車輪が路肩のレールに落ちるのを避けるため、道路の中心にやや近づいて通行すべきです',
        '如果是在所规定的速度范围内，就可以反复地进行急起动、急加速': '規定された速度範囲内であれば、急発進や急加速を繰り返してもよい',
        '想要超车时，首先必须确认该场所不是禁止超车的场所': '追い越しをしたいときは、まずその場所が追い越し禁止の場所でないことを確認しなければなりません',
        '由于自己没有驾驶执照，虽然知道朋友已经喝了酒，但还是求朋友开车将自己送到了家里': '自分に運転免許がないため、友人が酒を飲んだことを知っていたが、それでも友人に車で家まで送ってもらうよう頼んだ',
        '在有该标志的道路上，表示前方的路面不平': 'この標識がある道路では、前方の路面が平らでないことを示しています',
        '虽然公共汽车发出了信号起动了，但鸣笛后紧跟着前方车辆超越了公共汽车': 'バスが信号を出して発進したが、クラクションを鳴らした後、前方の車両に続いてバスを追い越した',
        '车辆总重量不满5,000kg、最大载重量不满3,000kg的货车用普通驾驶执照即可驾驶': '車両総重量5,000kg未満、最大積載量3,000kg未満の貨物自動車は普通免許で運転できます',
        '在住宅区行驶时，因为接近视野不好的小巷，所以鸣笛驶了过去': '住宅地を走行する際、見通しの悪い路地に接近したため、クラクションを鳴らして通過した',
        '自动变速车在上坡驻车时，要在踩住刹车踏板并拉住手刹后将变速杆切入P档': 'オートマチック車を上り坂で駐車する際は、ブレーキペダルを踏み、ハンドブレーキを引いた後、変速レバーをPに入れます',
        '该图所示的警察的手势信号对于箭头方向的交通而言，与红灯信号含义相同': 'この図に示された警察官の手信号は、矢印方向の交通にとって、赤信号と同じ意味を持ちます',
        '即使可以越入道路中心以右的部分通行，除了单行路以外，也必须尽量减少越入道路右侧的次数': '道路の中心から右側の部分に入って通行できる場合でも、一方通行路を除き、道路右側に入る回数をできるだけ減らさなければなりません',
        '在根据标志或标示指定要暂时停车的交叉路，如果没有其它车辆而且没有特别危险时，不需暂时停车': '標識や標示により一時停止が指定されている交差点でも、他の車両がなく、特に危険がない場合は、一時停止する必要はありません',
        '初学驾驶员（取得普通驾驶执照未经过1年者）驾驶从别人那里借来的普通汽车时，不用贴「初学者标记」': '初心者運転者（普通免許取得後1年未満の者）が他人から借りた普通自動車を運転する際は、「初心者マーク」を表示する必要はありません',
        '超车时，如果对前方车辆的行动或前方的交通等多少有一些不安，最好毫不犹豫地一气超过去': '追い越しの際、前方の車両の行動や前方の交通などに多少不安がある場合は、ためらわずに一気に追い越すのが最善です',
        '腰部安全带要勒紧髋部，并确认安全带是否扭曲': '腰のシートベルトは腰骨にしっかり締め、ベルトがねじれていないか確認します',
        '该标示表示此场所为「禁止掉头」的终点': 'この標示は、この場所が「転回禁止」の終点であることを示しています',
        '在公共汽车等优先通行带行驶时，虽然幼儿园班车接近，但由于不是公共汽车，所以照常行驶了': 'バスなどの優先通行帯を走行する際、幼稚園の送迎バスが接近したが、バスではないため、通常通り走行した',
        '如果与停止着的有轨电车的侧面间隔在1.5米以上，无论是否有人上下车都可以注意通过': '停車している路面電車との側面間隔が1.5メートル以上であれば、乗降の有無に関わらず、注意して通過できます',
        '在等信号停车时突然想起有急事而使用了手机，但因为对面的信号变绿了，所以边说话边起动了': '信号待ちで停車中に急用を思い出して携帯電話を使用したが、対向の信号が青に変わったため、話しながら発進した',
        '该标示表示前方有人行横道或自行车横道': 'この標示は、前方に横断歩道または自転車横断帯があることを示しています',
        '在用标志或标示指定为直行或左转弯等通行方向的交叉路，必须按所指定的方向行进': '標識や標示により直進または左折などの通行方向が指定されている交差点では、指定された方向に進まなければなりません',
        '因为有行人想横过人行横道所以暂时停了车，但由于有急事，鸣笛提醒行人注意后，比行人先行通过了': '歩行者が横断歩道を横断しようとしていたため一時停止したが、急用があったため、クラクションで歩行者に注意を促した後、歩行者より先に通過した',
        '即使是在前方车辆准备超越其前面的汽车时，只要能够确认前方的安全就可以超越这些车辆': '前方の車両がその前の自動車を追い越そうとしている場合でも、前方の安全を確認できれば、これらの車両を追い越すことができます',
        '在交叉路跟着前面的车右转弯时，如果前面的车已经发出信号的话，就不必发出右转弯的信号': '交差点で前方の車に続いて右折する際、前方の車がすでに信号を出している場合は、右折の信号を出す必要はありません',
        '该标志表示不得以超过时速50公里的速度行驶': 'この標識は、時速50キロメートルを超える速度で走行してはいけないことを示しています',
        '在为进出面向道路的场所而横过路侧带时，如有行人应缓行通过': '道路に面した場所への出入りのために路側帯を横断する際、歩行者がいる場合は徐行して通過すべきです',
        '驾驶员感觉到危险后刹车到制动器实际开始起作用之间的车辆行驶距离称为空走距离': '運転者が危険を感じてブレーキをかけてから、ブレーキが実際に効き始めるまでの車両の走行距離を空走距離と呼びます',
        '如果发出起车信号之前确认了前后左右安全的话，发出信号后，就不必再次确认安全': '発進信号を出す前に前後左右の安全を確認していれば、信号を出した後、再度安全を確認する必要はありません',
        '在行驶方向的前方有障碍物时，要提前暂时停车或减速，让对面驶来的车辆先通行': '走行方向の前方に障害物がある場合、事前に一時停止または減速し、対向車に先に通行させなければなりません',
        '正确地使用儿童安全椅，在发生交通事故时可以大大地减少伤害，同时可以防止儿童妨碍驾驶': 'チャイルドシートを正しく使用することで、交通事故発生時に傷害を大幅に減らすことができ、同時に子供が運転を妨げることを防ぐことができます',
        '该标示表示是禁止入内部分': 'この標示は、進入禁止部分であることを示しています',
        '打算在前方交叉路左转弯时，必须在临左转弯之前靠向道路的左端左转弯': '前方の交差点で左折する予定の場合は、左折の直前に道路の左端に寄って左折しなければなりません',
        '在停止的车辆旁通过时，不必连车内是否有人也注意': '停車している車両の横を通過する際は、車内に人がいるかどうかまで注意する必要はありません',
        '因为车辆横穿、掉头、倒车是妨碍交通顺畅的驾驶行为，所以必须充分注意不要妨碍行人和其它车辆的正常通行': '車両の横断、転回、後退は交通の流れを妨げる運転行為であるため、歩行者や他の車両の正常な通行を妨げないよう十分注意しなければなりません',
        '自动变速车的发动机刚起动时，因为发动机的转数升高，所以不踩紧刹车踏板操作会有急起动的危险': 'オートマチック車のエンジンが始動した直後は、エンジンの回転数が上がるため、ブレーキペダルをしっかり踏まないと急発進の危険があります',
        '警察用手势信号指挥交通时必须遵守，但由于交通巡查员不是警察，所以不遵守其手势信号也行': '警察が手信号で交通を指揮する際は従わなければなりませんが、交通巡視員は警察ではないため、その手信号に従う必要はありません',
        '只有在没有自行车通行的情况下，轻型摩托车才可以在自行车道通行': '自転車の通行がない場合のみ、原動機付自転車は自転車道を通行できます',
        '在交叉路左转弯时，应该充分注意靠向左侧通行的二轮摩托车，提前靠近道路的左端缓行，以免发生卷入事故': '交差点で左折する際は、左側を通行する自動二輪車に十分注意し、巻き込み事故を防ぐため、事前に道路の左端に近づいて徐行すべきです',
        '看到儿童在道路上玩时，只要鸣笛警告就可以不用缓行通过': '子供が道路上で遊んでいるのを見たときは、クラクションで警告すれば、徐行せずに通過できます',
        '在没有车辆通行带的隧道，不得为超越汽车或轻型摩托车改变车道或在其车辆旁边通过': '車両通行帯のないトンネルでは、自動車や原動機付自転車を追い越すために車線変更したり、その車両の横を通過したりしてはいけません',
        '发生交通事故时，刑事责任由驾驶员承担，但民事责任全部由所加入的保险公司承担': '交通事故が発生した場合、刑事責任は運転者が負いますが、民事責任はすべて加入している保険会社が負います',
        # 第三批翻译规则（日文）
        '即使是在有最高时速40公里标志的路段行驶，轻型摩托车的时速也不得超过30公里': '最高速度時速40キロメートルの標識がある区間を走行する場合でも、原動機付自転車の時速は30キロメートルを超えてはいけません',
        '开车时在行人旁边通过时，必须缓行保证行人安全': '運転中に歩行者の横を通過する際は、歩行者の安全を確保するため、必ず徐行しなければなりません',
        '在安全地带的旁边通过时，只在有行人时缓行就可以了': '安全地帯の横を通過する際は、歩行者がいるときだけ徐行すればよい',
        '从停车的机动车旁边通过时，有时车门会突然打开，或者突然从车后冲出行人，必须减速谨慎通行': '停車中の自動車の横を通過する際、ドアが突然開いたり、車の後ろから歩行者が突然飛び出したりすることがあるため、減速して慎重に通行しなければなりません',
        '从正在上下车的学校、幼儿园校车旁边通过时，必须暂时停车确认安全': '乗降中の学校・幼稚園の送迎バスの横を通過する際は、必ず一時停止して安全を確認しなければなりません',
        '对于贴有此图标的车，因为危险，禁止超车和追车': 'このアイコンを表示している車両は、危険なため、追い越しと追走が禁止されています',
        '准备在交叉路左转弯时，必须在转弯前约3秒钟发出左转弯的信号': '交差点で左折の準備をする際は、左折の約3秒前に左折の信号を出さなければなりません',
        '改变车道、掉头、倒车等行为结束时，必须在经过约3秒钟之后取消该信号': '車線変更、転回、後退などの行為が終了したときは、約3秒後にその信号を取り消さなければなりません',
        '即使是在用黄线划分车道通行带的地方，如果是为了左右转弯，就可以越过该线改变车道': '黄線で車線通行帯が区画されている場所でも、左右折のためであれば、その線を越えて車線変更できます',
        '在坡度大的下坡禁止超车，但是在坡度大的上坡不禁止超车': '急な下り坂では追い越しが禁止されていますが、急な上り坂では追い越しは禁止されていません',
        '交叉路及其跟前30米以内的场所，不能超车，但是在优先道路上行驶时可以超车': '交差点およびその手前30メートル以内の場所では追い越しはできませんが、優先道路を走行する際は追い越しできます',
        '在有图中标志的地方不能超车': '図中の標識がある場所では追い越しできません',
        '在视线较好的铁路道，如果可以确认安全，则可以缓行通过': '見通しの良い踏切では、安全を確認できれば、徐行して通過できます',
        '为紧急车辆让行时，即使在单行线上，也必须将车辆靠向道路左侧': '緊急車両に道を譲る際は、一方通行路であっても、車両を道路の左側に寄せなければなりません',
        '在设有公交车等专用车道的道路上，车辆（小型特殊机动车、轻型摩托车、轻型车辆），除在转弯等不得已的情况外，不可在该车道行驶': 'バスなどの専用車線が設置されている道路では、車両（小型特殊自動車、原動機付自転車、軽自動車）は、左右折などのやむを得ない場合を除き、その車線を走行してはいけません',
        '在交叉路按指定机动汽车道路行驶，即使有紧急车辆接近也可以不必让行': '交差点で指定された自動車専用道路を走行する際は、緊急車両が接近しても道を譲る必要はありません',
        '在前车要转弯、发出改变车道的信号时，除非必须急刹车或急打方向盘的情况外，不得妨碍其改变车道': '前方の車両が曲がろうとしたり、車線変更の信号を出したりするときは、急ブレーキや急ハンドルを切らなければならない場合を除き、その車線変更を妨げてはいけません',
        '腰部安全带如系在腹部而非腰部位置，一旦发生事故会受到强力压迫有危险，因此应该系在盆骨部位': '腰のシートベルトを腹部ではなく腰の位置に締めると、事故発生時に強い圧迫を受ける危険があるため、骨盤部に締めるべきです',
        '乘坐副驾驶座位的人必须使用安全带，但坐在后部座位的人不必使用': '助手席に座る人はシートベルトを使用しなければなりませんが、後部座席に座る人は使用する必要はありません',
        '在如图所示道路上，A车超B车时，不得超出中央线在右侧部分行驶': '図示の道路では、A車がB車を追い越す際、中央線を越えて右側部分を走行してはいけません',
        '同一方向有三条车道行驶带时，最右侧为超车用通行带，应让开行驶，车速慢的在左侧通行带行驶，车速快的在右侧通行带行驶': '同一方向に3車線の通行帯がある場合、最も右側は追い越し用通行帯で、空けて走行すべきです。速度の遅い車は左側通行帯を、速度の速い車は右側通行帯を走行します',
        '在不得已的情况下，可以在安全地带行驶': 'やむを得ない場合、安全地帯を走行できます',
        '在图中表示的地方，不越过右侧道路部分的时候可以超车': '図中に示された場所では、右側道路部分を越えない場合、追い越しできます',
        '有图中的车辆通行带的地方,可以按箭头指向改变车道': '図中の車両通行帯がある場所では、矢印の方向に従って車線変更できます',
        '图中的交叉路,属于 A 车一侧和 B 车一侧的视线都较差的交叉路,因此 A 和 B 车都必须缓行': '図中の交差点は、A車側とB車側の両方の見通しが悪い交差点であるため、A車とB車の両方が徐行しなければなりません',
        '图示禁止车辆进入，车辆可以从标志的对面(背面)进入,但是不得从正面通行': '図示は車両進入禁止を示しており、車両は標識の反対側（背面）から進入できますが、正面から通行してはいけません',
        '自动车的乘坐定员时，12 岁未满的孩子 2 人可以算作大人 1 人': '自動車の乗車定員では、12歳未満の子供2人は大人1人として計算できます',
        '持有普通驾驶执照的人,除可以驾驶普通机动车以外，还可以驾驶小型的特殊机动车和轻型摩托车': '普通免許を所持している者は、普通自動車を運転できるほか、小型特殊自動車と原動機付自転車も運転できます',
        '再雪地或结冰的道路等行驶的时候,必须使用轮胎防滑链或者冬季轮胎，防备打滑或者横向打滑等': '雪道や凍結した道路などを走行する際は、タイヤチェーンまたはスタッドレスタイヤを使用し、スリップや横滑りなどを防がなければなりません',
        '停在道路左侧的车辆起步时的信号,可以按与向右改变车道时相同的要领发出': '道路左側に停車している車両の発進時の信号は、右に車線変更するときと同じ要領で出すことができます',
        '自动变速车在启动发动机的时候,在启动发动机前要脚踏刹车踏板确定位置，用眼睛确认油门踏板位置等非常重要': 'オートマチック車でエンジンを始動する際は、エンジンを始動する前にブレーキペダルを踏んで位置を確認し、目でアクセルペダルの位置を確認することが非常に重要です',
        '进行摩托车的刹车操作时，不要打方向盘,使车体保持笔,同时使用前后轮制动器': 'バイクのブレーキ操作を行う際は、ハンドルを切らず、車体をまっすぐに保ち、前後輪のブレーキを同時に使用します',
        '改变车道的时候,如果后面的车不能避免急刹车或者急打方向盘的情况下,就不能改变车道': '車線変更の際、後続車が急ブレーキや急ハンドルを避けられない場合は、車線変更できません',
        '在靠着道路左侧步行道与步行道平行停着的车辆右侧不可以停泊车，但是可以临时停车': '道路左側の歩道に平行して停車している車両の右側には駐車できませんが、一時駐車はできます',
        '夜间与白天相比视野比较差,看不清行人和自行车等,会导致发现得太晚,所以行驶速度应该比白天慢': '夜間は昼間と比べて視界が悪く、歩行者や自転車などが見えにくく、発見が遅れる可能性があるため、走行速度は昼間より遅くすべきです',
        '两人同乘大型摩托车或普通摩托车等的时候,应该尽可能选择后部位置较为宽敞的车型': '大型バイクや普通バイクなどで2人乗りする際は、できるだけ後部座席が広い車種を選ぶべきです',
        '即使获得了普通摩托车驾驶执照,获得期间未满 1 年的人,在一般道路上不能带人驾驶普通摩托车': '普通自動二輪免許を取得しても、取得期間が1年未満の者は、一般道路で普通自動二輪車に人を乗せて運転することはできません',
        '准备在高速公路上通行时,为了避免由于燃料冷却水、发动机油不足而停止.必须特意检查': '高速道路を通行する準備をする際は、燃料、冷却水、エンジンオイルの不足により停止するのを避けるため、特に点検する必要があります',
        '用吊车吊起故障车的前轮或后轮牵引时，不需要驾驶员坐在故障车里': 'クレーンで故障車の前輪または後輪を吊り上げて牽引する場合、故障車に運転者が座る必要はありません',
        '踩刹车的时候，感觉到比较松弛的时候，说明刹车很起作用': 'ブレーキを踏むとき、比較的緩いと感じるときは、ブレーキがよく効いていることを示しています',
        '高速道路中微型汽车、轻型摩托车发动机的总排气量在 125cc 以下的车辆禁止通行': '高速道路では、軽自動車や原動機付自転車の総排気量が125cc以下の車両は通行禁止です',
        '检查证是很重要的资料,所以应该准备一份复印件放在车里备用，将原件好好保存': '検査証は重要な資料であるため、コピーを車内に保管し、原本は大切に保管すべきです',
        '车辆在有行人在旁边通过时，必须缓行保证行人安全': '車両が歩行者の横を通過する際は、歩行者の安全を確保するため、必ず徐行しなければなりません',
        '安全地带的左侧和它前后 10 米以内的场所虽然不能停,自车，但是可以临时停车': '安全地帯の左側とその前後10メートル以内の場所は駐車できませんが、一時駐車はできます',
        '行入专用道路,准许小型特殊机动车,轻型摩托车及轻型车通行': '歩行者専用道路では、小型特殊自動車、原動機付自転車、軽自動車の通行が許可されています',
        '为紧急车辆让行时,即使在单行线上，也必须将车辆靠向道路左侧': '緊急車両に道を譲る際は、一方通行路であっても、車両を道路の左側に寄せなければなりません',
        '在左侧部分的路面宽度在 6 米以上的道路,视线良好并且不会影响对面驶来的车的通行时，可以从道路右侧越线超车': '左側部分の路面幅が6メートル以上の道路では、見通しが良く、対向車の通行に影響しない場合、道路の右側から線を越えて追い越しできます',
        '在有步行道的道路上停车的时候,为了留出更宽的车道,最好将轮胎的一部分停在步行道上': '歩道のある道路に駐車する際は、より広い車道を確保するため、タイヤの一部を歩道に駐車するのが最善です',
        '在高速公路上准备从加速车道驶入干线车道时,必须注意后方驶来的车辆,而不是在干线车道上行驶的前方车辆': '高速道路で加速車線から本線車線に進入する準備をする際は、本線車線を走行している前方の車両ではなく、後方から来る車両に注意しなければなりません',
        '前面或出入前后 3 米以内的场所,如果是自己所拥有的车库或就可以停泊车': '出入口の前後3メートル以内の場所は、自分が所有する車庫であれば駐車できます',
        '由于安全带在发生交通事故时可以大大地减少伤害，驾驶后排座位有安全带的车的驾驶员让后排的同乘者也系上了安全带': 'シートベルトは交通事故発生時に傷害を大幅に減らすことができるため、後部座席にシートベルトがある車を運転する運転者は、後部座席の同乗者にもシートベルトを着用させました',
        '该标志指不仅是车辆，有轨电车和行人等都禁止通行': 'この標識は、車両だけでなく、路面電車や歩行者なども通行禁止であることを示しています',
        '刹车时，一开始就要尽量用力踩下去为好': 'ブレーキをかけるときは、最初からできるだけ強く踏み込むのがよい',
        '准备掉头或向右转弯时，必须在到达距其行为开始的地点的30米之前的地点时发出信号': '転回または右折の準備をする際は、その行為が始まる地点の30メートル前の地点に到達したときに信号を出さなければなりません',
        '取得第一种普通驾驶执照的人，即便是为了将出租车送回修理工场，也不可以驾驶': '第一種普通免許を取得した者でも、タクシーを修理工場に送り返す目的であっても運転することはできません',
        '该标示表示禁止进入其内停车': 'この標示は、その中に進入して駐車することを禁止しています',
        '由于交叉路及其附近是交通事故的多发场所，因此应该提速迅速地通过': '交差点およびその付近は交通事故が多発する場所であるため、速度を上げて迅速に通過すべきです',
        '只要取得普通驾驶执照，就可以驾驶最大载重量为4,000kg的货车和乘车定员为11大的乘用汽车': '普通免許を取得すれば、最大積載量4,000kgの貨物自動車と乗車定員11人の乗用自動車を運転できます',
        '驾驶员不仅需要掌握驾驶技术及知识，作为社会一员，对其他的道路利用者还需要有体谅的心态': '運転者は運転技術や知識を習得するだけでなく、社会の一員として、他の道路利用者に対して思いやりの心を持つ必要があります',
        '该标志表示车辆可以直行及左转弯，但不能右转弯': 'この標識は、車両が直進および左折できるが、右折できないことを示しています',
        '车辆不能在轨道线内通行，但右转弯、左转弯、横过、掉头等时可以在轨道线内横过': '車両は軌道線内を通行することはできませんが、右折、左折、横断、転回などの際は軌道線内を横断できます',
        '驾驶员感觉到危险踩刹车时，从制动开始起作用到车辆停止的距离称为停车距离': '運転者が危険を感じてブレーキをかけたとき、ブレーキが効き始めてから車両が停止するまでの距離を停止距離と呼びます',
        '在后方视野不好的场所或从狭窄的道路驶到宽阔道路等不得已倒车起动时，最好让同乘者帮助确认后方': '後方の視界が悪い場所や狭い道路から広い道路に出るなど、やむを得ず後退発進する際は、同乗者に後方を確認してもらうのが最善です',
        '在有障碍物的场所错车时，向有障碍物方向行驶的车辆可以优先通行': '障害物がある場所で行き違いをする際は、障害物の方向に向かって走行する車両が優先通行できます',
        '在有该标志的地方，因为有交叉路，所以必须鸣笛通行': 'この標識がある場所では、交差点があるため、警音器を鳴らして通行しなければなりません',
        '即使是在没有交通指示而且视野不好的交叉路，只要没有其它车辆就可以不用缓行通过': '交通指示がなく、見通しの悪い交差点でも、他の車両がなければ、徐行せずに通過できます',
        '取得临时驾驶执照的人如果在汽车所规定的位置上贴上临时驾驶执照练习标记，就可以为了练习而一个人驾驶': '仮免許を取得した者は、自動車の規定された位置に仮免許練習標識を貼れば、練習のために一人で運転できます',
        '原则上，车辆应该在道路中心（有中心线时，为中心线）以左的部分通行': '原則として、車両は道路の中心（中心線がある場合は中心線）より左側の部分を通行すべきです',
        '上车后关车门时，为了防止车门没关紧，最好用力一下关好': '乗車後ドアを閉める際は、ドアがしっかり閉まらないのを防ぐため、力強く閉めるのが最善です',
        '取得中型驾驶执照的人可以驾驶乘车定员为30人的巴士': '中型免許を取得した者は、乗車定員30人のバスを運転できます',
        '该标志下的辅助标牌表示上述主标志的交通限制地段': 'この標識の下の補助標識は、上記の主標識の交通規制区間を示しています',
        '在道路左侧被指定为公共汽车专用通行带的地方，即使是左转弯时，也不能在该车道通行': '道路の左側がバス専用通行帯に指定されている場所では、左折時であっても、その車線を通行することはできません',
        '在自动变速车使用发动机制动时，最好将变速杆切入2档或L档(或1档)': 'オートマチック車でエンジンブレーキを使用する際は、変速レバーを2速またはL速（または1速）に入れるのが最善です',
        '在行人旁边通过时必须与行人之间留出充分的间隔或缓行，但行人在路侧带时则没有必要': '歩行者の横を通過する際は、歩行者との間に十分な間隔を空けるか徐行しなければなりませんが、歩行者が路側帯にいる場合は必要ありません',
        '即使前方信号灯的信号是红色，也必须听从正在指挥交通的警察的右转弯或左转弯的指示': '前方の信号機の信号が赤色であっても、交通を指揮している警察官の右折または左折の指示に従わなければなりません',
        '道路中心线的左侧部分正在施工不能通行时，可以越入右侧部分通行': '道路の中心線の左側部分が工事中で通行できない場合、右側部分に入って通行できます',
        '由于铁路道对面交通拥挤，若照常行驶有可能在铁路道内停滞不动时，不得进入铁路道': '踏切の向こう側の交通が混雑しているため、通常通り走行すると踏切内で動けなくなる可能性がある場合は、踏切に入ってはいけません',
        '超车时，如果急加速或急打方向盘改变车道，就有可能导致方向盘失控或发生侧滑，所以必须充分注意': '追い越しの際、急加速や急ハンドルで車線変更すると、ハンドル操作が効かなくなったり横滑りが発生したりする可能性があるため、十分注意しなければなりません',
        '该标志表示前方道路是上陡坡': 'この標識は、前方の道路が急な上り坂であることを示しています',
        '右转弯时，必须尽量提前靠近道路的中心，紧贴交叉路中心的内侧（根据标志指定有通行场所时，在其指定的场所）缓行': '右折時は、できるだけ早く道路の中心に近づき、交差点の中心の内側（標識で通行場所が指定されている場合は、その指定された場所）に沿って徐行しなければなりません',
        '在为起动自动变速车而操作变速杆时，只要不松开加速踏板，就不用拉手刹或踩刹车踏板': 'オートマチック車を始動するために変速レバーを操作する際は、アクセルペダルを離さない限り、ハンドブレーキを引いたりブレーキペダルを踏んだりする必要はありません',
        '在根据标志或标示禁止横穿或掉头的地点，即使没有行人或其它车辆也不得横穿或掉头': '標識や標示により横断または転回が禁止されている場所では、歩行者や他の車両がなくても、横断または転回してはいけません',
        '接近交叉路前的停车位置时，前方的信号变成了黄灯，此时只有在无法安全停车的情况下才可以不停车通过交叉路': '交差点の手前の停止位置に接近する際、前方の信号が黄色に変わったときは、安全に停止できない場合のみ、停止せずに交差点を通過できます',
        '在交叉路附近行驶时，因为紧急车辆接近，所以没有进入交叉路，而是靠道路的左侧暂时停了下来': '交差点付近を走行する際、緊急車両が接近したため、交差点に入らず、道路の左側に寄せて一時停止しました',
        '刹车时，刚一开始要尽量轻踩，然后慢慢地踩到需要的强度': 'ブレーキをかけるときは、最初はできるだけ軽く踏み、その後徐々に必要な強さまで踏み込みます',
        '在交通量少的交叉路，在交叉路近前发出右转弯或左转弯的信号即可': '交通量の少ない交差点では、交差点の手前で右折または左折の信号を出せばよい',
        '最大载重量为4,000kg的货车用普通驾驶执照即可驾驶': '最大積載量4,000kgの貨物自動車は普通免許で運転できます',
        '饮酒后不得驾驶，若是酒精度数低的啤酒，喝了以后驾驶也无妨': '飲酒後は運転してはいけませんが、アルコール度数が低いビールであれば、飲んだ後でも運転してもよい',
        '该标志表示道路到前方已是尽头': 'この標識は、道路が前方で行き止まりであることを示しています',
        '轻型摩托车和小型特殊汽车可以在公共汽车专用通行带通行，但大型二轮摩托车等除了左转弯或不得已的情况以外不能通行': '原動機付自転車と小型特殊自動車はバス専用通行帯を通行できますが、大型自動二輪車などは左折時またはやむを得ない場合を除き、通行できません',
    }
    
    # 先匹配完整句子（按长度降序排列，优先匹配长句子）
    sorted_translations_ja = sorted(full_sentence_translations_ja.items(), key=lambda x: len(x[0]), reverse=True)
    for zh, ja in sorted_translations_ja:
        if zh in result:
            result = result.replace(zh, ja)
            break  # 只替换第一个匹配的
    
    # 基础词汇翻译（日文）
    basic_translations = {
        '该标志': 'この標識',
        '表示': '示しています',
        '禁止': '禁止',
        '注意': '注意',
        '必须': 'しなければなりません',
        '不得': 'してはいけません',
        '可以': 'できます',
        '应该': 'すべきです',
        '需要': '必要があります',
        '最好': '最善です',
        '驾驶': '運転',
        '车辆': '車両',
        '道路': '道路',
        '交叉路': '交差点',
        '人行横道': '横断歩道',
        '信号灯': '信号機',
        '绿灯': '青信号',
        '红灯': '赤信号',
        '黄灯': '黄色信号',
        '右转弯': '右折',
        '左转弯': '左折',
        '超车': '追い越し',
        '停车': '駐車',
        '行驶': '走行',
        '通行': '通行',
        '行人': '歩行者',
        '自行车': '自転車',
        '摩托车': 'バイク',
        '汽车': '自動車',
        '公共汽车': 'バス',
        '出租车': 'タクシー',
        '刹车': 'ブレーキ',
        '加速': '加速',
        '减速': '減速',
        '缓行': '徐行',
        '速度': '速度',
        '安全': '安全',
        '危险': '危険',
        '执照': '免許',
        '驾驶执照': '運転免許',
        '标志': '標識',
        '标示': '標示',
        '警察': '警察',
        '前方': '前方',
        '后方': '後方',
        '左侧': '左側',
        '右侧': '右側',
        '中心线': '中心線',
        '车道': '車線',
        '路口': '交差点',
        '铁路道': '踏切',
        '坡道': '坂道',
        '上坡': '上り坂',
        '下坡': '下り坂',
    }
    
    # 按长度降序排列，先替换长的短语
    sorted_translations = sorted(basic_translations.items(), key=lambda x: len(x[0]), reverse=True)
    
    for zh, ja in sorted_translations:
        result = result.replace(zh, ja)
    
    # 清理格式
    result = re.sub(r'\s+', ' ', result).strip()
    
    return prefix + result

def main():
    # 读取文件
    print("读取文件...")
    with open('src/data/questions/zh/questions_auto_tag.json', 'r', encoding='utf-8') as f:
        questions = json.load(f)
    
    print(f"总问题数: {len(questions)}")
    
    # 处理所有问题
    print("开始翻译...")
    translated_count = 0
    
    for i, q in enumerate(questions):
        # 处理content
        if q.get('content'):
            zh = q['content'].get('zh', '')
            
            # 翻译en
            if zh:
                en = q['content'].get('en', '')
                if not en or en.strip() == '' or is_chinese_only(en):
                    q['content']['en'] = translate_zh_to_en(zh)
                    translated_count += 1
            
            # 翻译ja
            if zh:
                ja = q['content'].get('ja', '')
                if not ja or ja.strip() == '' or is_chinese_only(ja):
                    q['content']['ja'] = translate_zh_to_ja(zh)
                    translated_count += 1
        
        # 处理explanation
        if q.get('explanation'):
            zh = q['explanation'].get('zh', '')
            
            # 翻译en
            if zh:
                en = q['explanation'].get('en', '')
                if not en or en.strip() == '' or is_chinese_only(en):
                    q['explanation']['en'] = translate_zh_to_en(zh)
                    translated_count += 1
            
            # 翻译ja
            if zh:
                ja = q['explanation'].get('ja', '')
                if not ja or ja.strip() == '' or is_chinese_only(ja):
                    q['explanation']['ja'] = translate_zh_to_ja(zh)
                    translated_count += 1
        
        if (i + 1) % 100 == 0:
            print(f"已处理 {i + 1}/{len(questions)} 个问题... (翻译: {translated_count})")
    
    # 保存文件
    print("保存文件...")
    with open('src/data/questions/zh/questions_auto_tag.json', 'w', encoding='utf-8') as f:
        json.dump(questions, f, ensure_ascii=False, indent=2)
    
    print(f"完成！共翻译了 {translated_count} 个字段。")
    
    # 验证
    print("\n验证翻译结果...")
    remaining = 0
    for q in questions:
        if q.get('content'):
            en = q['content'].get('en', '')
            ja = q['content'].get('ja', '')
            if not en or not ja or is_chinese_only(en) or is_chinese_only(ja):
                remaining += 1
        if q.get('explanation'):
            en = q['explanation'].get('en', '')
            ja = q['explanation'].get('ja', '')
            if not en or not ja or is_chinese_only(en) or is_chinese_only(ja):
                remaining += 1
    
    print(f"剩余需要翻译的字段: {remaining}")
    if remaining == 0:
        print("✅ 所有翻译已完成！")
    else:
        print(f"❌ 还有 {remaining} 个字段需要翻译")

if __name__ == '__main__':
    main()

